######################################################################################################
# @Leroyby
# Original Repo : https://github.com/Leroyby/Homeassistant-Config
# Automation away mode 
######################################################################################################
- alias: Mode_armed_on
  trigger:
    - platform: state
      entity_id: input_boolean.armed_mode
      to: 'on'
  condition: []
  action:
  - service: alarmo.arm
    data:
      entity_id: alarm_control_panel.alarmo
      code: !secret alarm_code
      mode: away 
      skip_delay: true
  mode: single

- alias: Mode_armed_off
  trigger:
    - platform: state
      entity_id: 
      - input_boolean.armed_mode
      to: 'off'
  condition: []
  action:
  - service: alarmo.disarm
    data:
      entity_id: alarm_control_panel.alarmo
      code: !secret alarm_code
      skip_delay: true
  mode: single  


