######################################################################################################
# @Leroyby
# Original Repo : https://github.com/Leroyby/Homeassistant-Config
# Automation away mode 
######################################################################################################
- alias: Mode_Away_on
  trigger:
    - platform: state
      entity_id: 
      - binary_sensor.no_one_home
      - input_boolean.away_mode
      to: 'on'
  condition: []
  action:
  - service: input_boolean.turn_off
    target:
      entity_id: 
      - input_boolean.work_mode
      - input_boolean.normal_mode
      - input_boolean.gaming_mode
      - input_boolean.night_mode
  - service: script.bedroom_off
  - service: script.office_off
  - service: script.living_room_off
  - service: alarmo.arm
    data:
      entity_id: alarm_control_panel.alarmo
      code: !secret alarm_code
      mode: away
  mode: single


