######################################################################################################REDACTED
# @LeroybyREDACTED
# Original Repo : https://github.com/Leroyby/Homeassistant-ConfigREDACTED
# Automation away mode REDACTED
######################################################################################################REDACTED
- alias: Mode_Away_onREDACTED
  id: 9521d521-00dc-4116-b467-5150735fcffREDACTED
  trigger:REDACTED
    - platform: stateREDACTED
      entity_id: REDACTED
      - input_boolean.away_modeREDACTED
      to: 'on'REDACTED
      for: '00:15:00'REDACTED
  condition: []REDACTED
  action:REDACTED
  - service: input_boolean.turn_offREDACTED
    target:REDACTED
      entity_id: REDACTED
      - input_boolean.work_modeREDACTED
      - input_boolean.normal_modeREDACTED
      - input_boolean.gaming_modeREDACTED
      - input_boolean.night_modeREDACTED
  - service: script.bedroom_offREDACTED
  - service: script.office_offREDACTED
  - service: script.living_room_offREDACTED
  mode: single