######################################################################################################
# @Leroyby
# Original Repo : https://github.com/Leroyby/Homeassistant-Config
# Automation away mode 
######################################################################################################
- alias: Mode Away on
  id: 9521d521-00dc-4116-b467-5150735fcff9
  trigger:
    - platform: state
      entity_id: 
      - input_boolean.away_mode
      to: 'on'
  condition: []
  action:
  - service: input_boolean.turn_off
    target:
      entity_id: 
      - input_boolean.work_mode
      - input_boolean.normal_mode
      - input_boolean.gaming_mode
      - input_boolean.night_mode
  - service: script.bedroom_off
  - service: script.office_off
  - service: script.living_room_off
  mode: single