######################################################################################################
# @Leroyby
# Original Repo : https://github.com/Leroyby/Homeassistant-Config
# Automation away mode 
######################################################################################################
- alias: Mode_Away_on
  trigger:
    - platform: state
      entity_id: 
      - input_boolean.away_mode
      to: 'on'
  condition: []
  action:
  - service: input_boolean.turn_off
    target:
      entity_id: 
      - input_boolean.normal_mode
      - input_boolean.work_mode
      - input_boolean.gaming_mode
      - input_boolean.night_mode
  - service: input_boolean.turn_on
    target:
      entity_id: 
      - input_boolean.armed_mode
  - service: script.bedroom_off
  - service: script.office_off
  - service: script.living_room_off
  mode: single

- alias: Mode_Away_on_safety_arm_alarm
  trigger:
    - platform: time_pattern
      # Matches every 3 hours
      hours: 3
  condition: and
  conditions:
    - condition: state
      entity_id: "binary_sensor.no_one_home"
      state: "on"
    - condition: state
      entity_id: alarm_control_panel.alarmo
      state: disarmed
  action:
  - service: input_boolean.turn_on
    target:
      entity_id: 
      - input_boolean.armed_mode
  mode: single


