######################################################################################################
# @Leroyby
# Original Repo : https://github.com/Leroyby/Homeassistant-Config
# Automations night mode
######################################################################################################
- alias: Mode_night_on
  description: 'Turning everything down for night mode (except bedroom)'
  trigger:
  - platform: state
    entity_id:
    - input_boolean.night_mode
    to: 'on'
  condition: []
  action:
  - service: input_boolean.turn_off
    target:
      entity_id: 
      - input_boolean.normal_mode
      - input_boolean.gaming_mode
      - input_boolean.away_mode
      - input_boolean.work_mode
      - input_boolean.armed_mode
  - service: script.office_off
  - service: script.living_room_off
  mode: single
