- id: '1668367304644'
  alias: Bedroom Button
  description: ''
  use_blueprint:
    path: EPMatt/ikea_e1812.yaml
    input:
      integration: Zigbee2MQTT
      controller_device: dff73f19aab0d896445eb69e0b797d49
      controller_entity: sensor.button_bedroom_action
      helper_last_controller_event: input_text.bedroom_ikea_button
      action_button_short:
      - service: light.toggle
        data: {}
        target:
          entity_id: light.bedroom_lights
      action_button_double: []
      action_button_long:
      - service: light.toggle
        data:
          transition: 3
          color_temp: 414
        target:
          device_id: c1dc928aea9849e3bc6ae748eeaaef3f
      button_double_press: false
      button_long_loop: false
      helper_double_press_delay: 500
