######################################################################################################
# @Leroyby
# Original Repo : https://github.com/leroyby/Homeassistant-Config
# configuration.yaml
######################################################################################################
# Loads default set of integrations. Do not remove.
default_config:
frontend:
  themes: !include_dir_merge_named themes
# Text to speech
tts:
  - platform: google_translate
my:
# Alarm Panel
alarm_control_panel:
  - platform: manual
    name: Home Alarm
    code: !secret alarm_code
    code_arm_required: false
    arming_time: 45
    delay_time: 30
    disarm_after_trigger: false
    disarmed:
      trigger_time: 0
    armed_home:
      arming_time: 0
      delay_time: 0

# Inputs
input_datetime: !include input/input_datetimes.yaml
binary_sensor: !include_dir_merge_list binary_sensors
#input_number: !include input/input_numbers.yaml
input_select: !include input/input_selects.yaml
input_boolean: !include input/input_booleans.yaml
input_text: !include input/input_text.yaml
switch: !include_dir_merge_list switch
schedule: !include_dir_merge_list schedule
sensor: !include_dir_merge_list sensors
scene: !include_dir_merge_list scene
utility_meter: !include_dir_merge_list utilities
automation: !include automations.yaml
automation manual: !include_dir_merge_list automations
homeassistant:
  packages: !include_dir_named packages
light: !include groups/light_groups.yaml
script: !include_dir_merge_named scripts
timer: !include_dir_merge_named timers
device_tracker: !include includes/device_trackers.yaml
readme:
  convert_lovelace: true
lovelace:
  mode: storage
   # Add yaml dashboards
  dashboards:
    lovelace-yaml:
      mode: yaml
      title: Dashboard
      icon: mdi:script
      show_in_sidebar: true
      filename: uiv2/uiv2-lovelace.yaml
powercalc:
  create_utility_meters: true
recorder:
  db_url: !secret mariadb_url
  purge_keep_days: 30
  commit_interval: 20
duckdns:
  domain: !secret duckdns_url
  access_token: !secret duckdns_token
http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  ip_ban_enabled: true
  login_attempts_threshold: 3


