######################################################################################################
# @USER1by
# Original Repo : https://github.com/USER1by/Homeassistant-Config
# Lights group yaml file
######################################################################################################

- platform: group
  name: All Lights 
  unique_id: 2210062341
  entities:
    - light.bedroom_lights
    - light.living_room_lights
    - light.office_wiz_lights_ceiling
    - light.bad_klein
    - light.livingroom_deckenfluter_Tv
    
- platform: group
  name: Office_Lights
  unique_id: 2210062342
  entities:
    - light.wiz_office_1
    - light.wiz_office_2
    - light.wiz_office_3
    
- platform: group
  name: bedroom_lights
  unique_id: 2210062343
  entities:
    - light.decke_l1
    - light.decke_l2
    - light.decke_l3
    
- platform: group
  name: Livingroom lights
  unique_id: 2210062344
  entities:
    - light.livingroom_sofa
    - light.livingroom_table
    - light.livingroom_tv