######################################################################################################
# @Leroyby
# Original Repo : https://github.com/Leroyby/Homeassistant-Config
# Automation Notification Climate
######################################################################################################

## Living Room
- alias: Temperature Living area low Notification
  trigger:
    - platform: numeric_state
      entity_id: sensor.temperature_livingroom_average
      below: '20'
      for: '00:05:00'
  condition: []
  action:
    - service: notify.mobile_app_iphone_von_leroy
      data:
        title: "Temperatur living area low"
        message: "Die Temperatur im Wohnzimmer ist unter 20 Grad" 
  mode: single

- alias: Temperature living area high Notification
  trigger:
    - platform: numeric_state
      entity_id: sensor.temperature_livingroom_average
      above: '22.5'
      for: '00:02:00'
  condition: []
  action:
    - service: notify.mobile_app_iphone_von_leroy
      data:
        title: "Temperatur living area high"
        message: "Die Temperatur im Wohnzimmer 端ber 22.5 Grad" 
  mode: single  

 ## Office 
- alias: Temperature office low Notification
  trigger:
    - platform: numeric_state
      entity_id: sensor.temperature_office_average
      below: '20'
      for: '00:02:00'
  condition: []
  action:
    - service: notify.mobile_app_iphone_von_leroy
      data:
        title: "Temperatur office low"
        message: "Die Temperatur im B端ro unter 20 Grad" 

- alias: Temperature office high Notification
  trigger:
    - platform: numeric_state
      entity_id: sensor.temperature_office_average
      above: '23'
      for: '00:02:00'
  condition: []
  action:
    - service: notify.mobile_app_iphone_von_leroy
      data:
        title: "Temperatur office high"
        message: "Die Temperatur im B端ro 端ber 23 Grad" 