######################################################################################################
# @Leroyby
# Original Repo : https://github.com/Leroyby/Homeassistant-Config
# Automation Vacuum
######################################################################################################
- alias: Vacuum start away
  trigger:
    platform: state
    entity_id: binary_sensor.no_one_home
    to: 'on'
  condition:
  - condition: state
    entity_id: input_boolean.vacuum_ran
    state: "off"
  - condition: time
    after: "07:00:00"
    before: "20:00:00"  
  action:
  - service: script.vacuum_start
  - service: input_boolean.turn_on
    target:
      entity_id: input_boolean.vacuum_ran

- alias: Vacuum start away safety run
  trigger:
    - platform: time
      at: "11:00:00"
  condition:
  - condition: state
    entity_id: input_boolean.vacuum_ran
    state: "off"
  - condition: state
    entity_id: binary_sensor.no_one_home
    state: 'on'
  action:
  - service: script.vacuum_start
  - service: input_boolean.turn_on
    target:
      entity_id: input_boolean.vacuum_ran

# Reset Vacum reset binary switch "ran" every evening
- alias: Vacuum reset vacuum_ran sensor
  trigger:
    - platform: time
      at: "23:45:00"
  condition:
  action:
  - service: input_boolean.turn_off
    target:
      entity_id: input_boolean.vacuum_ran