######################################################################################################REDACTED
# @LeroybyREDACTED
# Original Repo : https://github.com/Leroyby/Homeassistant-ConfigREDACTED
# Automation VacuumREDACTED
######################################################################################################REDACTED
- alias: Vacuum start awayREDACTED
  trigger:REDACTED
    platform: stateREDACTED
    entity_id: binary_sensor.no_one_homeREDACTED
    to: 'on'REDACTED
  condition:REDACTED
  - condition: stateREDACTED
    entity_id: input_boolean.vacuum_ranREDACTED
    state: "off"REDACTED
  - condition: timeREDACTED
    after: "09:00:00"REDACTED
    before: "20:00:00"  REDACTED
  action:REDACTED
  - service: script.vacuum_startREDACTED
  - service: input_boolean.turn_onREDACTED
    target:REDACTED
      entity_id: input_boolean.vacuum_ranREDACTED
REDACTED
# Reset Vacum ran every eveningREDACTED
- alias: Vacuum reset vacuum_ran sensorREDACTED
  trigger:REDACTED
    - platform: timeREDACTED
      at: "23:45:00"REDACTED
  condition:REDACTED
  action:REDACTED
  - service: input_boolean.turn_offREDACTED
    target:REDACTED
      entity_id: input_boolean.vacuum_ran