######################################################################################################
# @Leroyby
# Original Repo : https://github.com/Leroyby/Homeassistant
# Vacuum
######################################################################################################
- alias: start cleaning
  trigger:
    - platform: time_pattern
      #This will match every 15 minutes
      minutes: "/15"
  condition:
  - condition: time
    after: 08:00:00
    before: '22:00:00'
  - condition: state
    entity_id: input_boolean.away_mode
    state: 'on'
  action:
  - service: vacuum.turn_on
    entity_id: vacuum.rombacus
  - service: input_boolean.turn_on
    target:
      entity_id: input_boolean.vacuum_ran

# Reset Vacum ran every evening
- alias: reset vacuum_ran
  trigger:
    - platform: time
      at: "23:00:00"
  condition:
  action:
  - service: input_boolean.turn_off
    target:
      entity_id: input_boolean.vacuum_ran