######################################################################################################
# @Leroyby
# Original Repo : https://github.com/Leroyby/Homeassistant-Config
# Automation Vacuum
######################################################################################################
- alias: Vacuum start away
  trigger:
    platform: state
    entity_id: input_boolean.away_mode
    to: 'on'
  condition:
  - condition: state
    entity_id: input_boolean.vacuum_ran
    state: "off"
  - condition: time
    after: "06:00:00"
    before: "20:00:00"  
  action:
  - service: script.vacuum_start
  - service: input_boolean.turn_on
    target:
      entity_id: input_boolean.vacuum_ran

- alias: Vacuum start away safety run
  trigger:
    - platform: time
      at: "11:15:00"
  condition:
  - condition: state
    entity_id: input_boolean.vacuum_ran
    state: "off"
  - condition: state
    entity_id: binary_sensor.no_one_home
    state: 'on'
  action:
  - service: script.vacuum_start
  - service: input_boolean.turn_on
    target:
      entity_id: input_boolean.vacuum_ran

# Reset Vacum reset binary switch "ran" every evening
- alias: Vacuum reset vacuum_ran sensor
  trigger:
    - platform: time
      at: "23:45:00"
  condition:
  action:
  - service: input_boolean.turn_off
    target:
      entity_id: input_boolean.vacuum_ran

- alias: Vacuum home
  trigger:
    - platform: state
      entity_id: vacuum.rombacus
      to: 'docked'
    - platform: state
      entity_id: vacuum.rombacus
      to: 'paused'
    - platform: state
      entity_id: vacuum.rombacus
      to: 'error'
    - platform: state
      entity_id: vacuum.rombacus
      to: 'idle'
  condition:
  action:
  - service: light.turn_off
    target:
      entity_id: 
      - light.Living_room_lights

- alias: Vacuum running
  trigger:
    - platform: state
      entity_id: vacuum.rombacus
      to: 'cleaning'
    - platform: state
      entity_id: vacuum.rombacus
      to: 'returning'
  condition: time
  after: "23:00:00"
  before: "06:00:00"
  action:
  - service: light.turn_on
    target:
      entity_id: 
      - light.Living_room_lights