######################################################################################################
# @Leroyby
# Original Repo : https://github.com/Leroyby/Homeassistant
# Set away modes
######################################################################################################
- alias: set away mode on presence
  trigger:
    - platform: time_pattern
      #This will match every 15 minutes
      minutes: "/5"
  condition:
  - condition: time
    after: 06:00:00
    before: '23:00:00'
  - condition: and
    conditions:
      - condition: state
        entity_id: person.leroy
        state: "away"
      - condition: state
        entity_id: person.USER2
        state: "away"
  action:
  - service: input_boolean.turn_on
    target:
      entity_id: input_boolean.away_mode