######################################################################################################
# @Leroyby
# Original Repo : https://github.com/Leroyby/Homeassistant-Config
# Automation Climate 
######################################################################################################

# Automation climate temp out: >=20 - off, <20 - 20, <5 - 21, <0 - REDACTED
    
- alias: climate bedroom shutdown window open
  trigger:
    - platform: state
      entity_id: binary_sensor.contact_bedroom_window_contact
      to: "on"
  action:
#    - service: climate.set_hvac_mode
#      target:
#        entity_id: climate.bedroom_thermostat
#      data:
#        hvac_mode: "off"
    - service: climate.set_temperature
      target:
        entity_id: climate.bedroom_thermostat
      data:
        temperature: 15
        hvac_mode: aus

- alias: climate bedroom reset heating window closed
  trigger:
    - platform: state
      entity_id: binary_sensor.contact_bedroom_window_contact
      to: "off"
  condition: []
  action:
    - service: climate.set_temperature
      target:
        entity_id: climate.bedroom_thermostat
      data:
        temperature: 20
        hvac_mode: auto
        
- alias: climate bedroom away
  trigger:
    - platform: state
      entity_id: binary_sensor.away_mode
      to: "on"
  action:
    - service: climate.set_temperature
      target:
        entity_id: climate.bedroom_thermostat
      data:
        temperature: 15
        hvac_mode: auto

- alias: climate bedroom getting home
  trigger:
    - platform: state
      entity_id: binary_sensor.no_one_home
      to: "off"
  action:
    - service: climate.set_temperature
      target:
        entity_id: climate.bedroom_thermostat
      data:
        temperature: 17
        hvac_mode: auto