######################################################################################################
# @Leroyby
# Original Repo : https://github.com/Leroyby/Homeassistant-Config
# Automation Climate 
######################################################################################################

# Automation climate temp out: >=20 - off, <20 - 20, <5 - 21, <0 - REDACTED
    
- alias: climate bedroom shutdown window open
  trigger:
    - platform: state
      entity_id: binary_sensor.contact_bedroom_window_contact
      to: "on"
  action:
    - service: climate.set_hvac_mode
      target:
        entity_id: climate.bedroom_thermostat
      data:
        hvac_mode: "off"

- alias: climate bedroom reset heating window closed
  trigger:
    - platform: state
      entity_id: binary_sensor.contact_bedroom_window_contact
      to: "off"
  condition: []
  action:
    - service: climate.set_preset_mode
      target:
        entity_id: climate.bedroom_thermostat
      data:
        hvac_mode: "manual"   
        
- alias: climate bedroom no one home
  trigger:
    - platform: state
      entity_id: binary_sensor.no_one_home
      to: "on"
  action:
    - service: climate.set_preset_mode
      target:
        entity_id: climate.bedroom_thermostat
      data:
        preset_mode: 'eco'

- alias: climate bedroom getting home
  trigger:
    - platform: state
      entity_id: binary_sensor.no_one_home
      to: "on"
  action:
    - service: climate.set_preset_mode
      target:
        entity_id: climate.bedroom_thermostat
      data:
        preset_mode: 'manual'     


