######################################################################################################
# @Leroyby
# Original Repo : https://github.com/Leroyby/Homeassistant-Config
# Automation Climate 
# https://pelaxa.com/blog/2022/04/10/automating-your-home-climate-control-with-home-assistant/
######################################################################################################

## Bedroom
- alias: shutdown heating
  trigger:
    - platform: numeric_state
      entity_id: sensor.hq_by_zofingen_realfeel_temperature
      above: '20'
      for: '24:00:00'
  condition: []
  action:
    - service: climate.set_hvac_mode
      target:
        entity_id: climate.bedroom_thermostat
      data:
        hvac_mode: "off" 

- alias: start heating
  trigger:
    - platform: numeric_state
      entity_id: sensor.hq_by_zofingen_realfeel_temperature
      below: '20'
      for: '24:00:00'
  condition: []
  action:
    - service: climate.set_hvac_mode
      target:
        entity_id: climate.bedroom_thermostat
      data:
        hvac_mode: auto
