######################################################################################################REDACTED
# @LeroybyREDACTED
# Original Repo : https://github.com/Leroyby/Homeassistant-ConfigREDACTED
# Automation Notification TemperatureREDACTED
######################################################################################################REDACTED
REDACTED
## BedroomREDACTED
- alias: Temperature Bedroom low NotificationREDACTED
  trigger:REDACTED
    - platform: numeric_stateREDACTED
      entity_id: sensor.temperature_bedroomREDACTED
      below: '19'REDACTED
      for: '00:02:00'REDACTED
  condition: []REDACTED
  action:REDACTED
    - service: notify.mobile_app_iphone_von_leroyREDACTED
      data:REDACTED
        title: "Temperatur Bedroom low"REDACTED
        message: "Die Temperatur im Schlafzimmer ist unter 19 Grad" REDACTED
  mode: singleREDACTED
REDACTED
- alias: Temperature Bedroom high NotificationREDACTED
  trigger:REDACTED
    - platform: numeric_stateREDACTED
      entity_id: sensor.temperature_bedroomREDACTED
      above: '21.0'REDACTED
      for: '00:02:00'REDACTED
  condition: []REDACTED
  action:REDACTED
    - service: notify.mobile_app_iphone_von_leroyREDACTED
      data:REDACTED
        title: "Temperatur Bedroom high"REDACTED
        message: "Die Temperatur im Schlafzimmer über 21 Grad" REDACTED
  mode: single  REDACTED
REDACTED
 ## Living RoomREDACTED
- alias: Temperature Living area low NotificationREDACTED
  trigger:REDACTED
    - platform: numeric_stateREDACTED
      entity_id: sensor.temperature_livingroom_averageREDACTED
      below: '20'REDACTED
      for: '00:05:00'REDACTED
  condition: []REDACTED
  action:REDACTED
    - service: notify.mobile_app_iphone_von_leroyREDACTED
      data:REDACTED
        title: "Temperatur living area low"REDACTED
        message: "Die Temperatur im Wohnzimmer ist unter 20 Grad" REDACTED
  mode: singleREDACTED
REDACTED
- alias: Temperature living area high NotificationREDACTED
  trigger:REDACTED
    - platform: numeric_stateREDACTED
      entity_id: sensor.temperature_livingroom_averageREDACTED
      above: '22.5'REDACTED
      for: '00:02:00'REDACTED
  condition: []REDACTED
  action:REDACTED
    - service: notify.mobile_app_iphone_von_leroyREDACTED
      data:REDACTED
        title: "Temperatur living area high"REDACTED
        message: "Die Temperatur im Wohnzimmer über 22.5 Grad" REDACTED
  mode: single  REDACTED
REDACTED
 ## Office REDACTED
- alias: Temperature office low NotificationREDACTED
  trigger:REDACTED
    - platform: numeric_stateREDACTED
      entity_id: sensor.temperature_office_averageREDACTED
      below: '20'REDACTED
      for: '00:02:00'REDACTED
  condition: []REDACTED
  action:REDACTED
    - service: notify.mobile_app_iphone_von_leroyREDACTED
      data:REDACTED
        title: "Temperatur office low"REDACTED
        message: "Die Temperatur im Büro unter 20 Grad" REDACTED
REDACTED
- alias: Temperature office high NotificationREDACTED
  trigger:REDACTED
    - platform: numeric_stateREDACTED
      entity_id: sensor.temperature_office_averageREDACTED
      above: '23'REDACTED
      for: '00:02:00'REDACTED
  condition: []REDACTED
  action:REDACTED
    - service: notify.mobile_app_iphone_von_leroyREDACTED
      data:REDACTED
        title: "Temperatur office high"REDACTED
        message: "Die Temperatur im Büro über 23 Grad" 