######################################################################################################
# @Leroyby
# Original Repo : https://github.com/Leroyby/Homeassistant-Config
# Automations Mediaplayer Bedroom
######################################################################################################

- alias: Media_Player start timer TV Bedroom
  trigger:
    platform: state
    entity_id: binary_sensor.bedroom_tv_on
    to: 'off'
  condition: 
  action:
  - service: timer.start
    target:
      entity_id: timer.bedroom_tv

- alias: "Timerstop tv bedroom"
  id: "Timerstop"
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.bedroom_tv
  action:
  - service: switch.turn_off
    target:
      entity_id: 
      - switch.bedroom_tv

- alias: Media_Player restart timer TV Livingroom
  trigger:
    platform: state
    entity_id: binary_sensor.bedroom_tv_on
    to: 'on'
  condition: 
  action:
  - service: timer.cancel
    target:
      entity_id: timer.bedroom_tv