######################################################################################################
# @USER1by
# Original Repo : https://github.com/USER1by/Homeassistant-Config
# Automations Mediaplayer Livingroom
######################################################################################################
- alias: Start TV Living Room
  trigger:
    platform: state
    entity_id: sensor.tv_button_switch_livingroom_click
    to: 'on'
  condition:
  action:
  - service: switch.turn_on
    target:
      entity_id: 
      - switch.livingroom_tv

- alias: Shutdown TV Living Room
  trigger:
    platform: state
    entity_id: sensor.tv_button_switch_livingroom_click
    to: 'off'
  condition:
  action:
  - service: switch.turn_off
    target:
      entity_id: 
      - switch.livingroom_tv