######################################################################################################
# @Leroyby
# Original Repo : https://github.com/Leroyby/Homeassistant-Config
# Automations Mediaplayer Livingroom
######################################################################################################

- alias: Media_Player start timer TV Livingroom
  trigger:
    platform: state
    entity_id: binary_sensor.activity_in_livingroom
    to: 'off'
    for: 
      hours: 1
  condition: []
  action:
  - service: timer.start
    target:
      entity_id: timer.livingroom_tv

- alias: "Timerstop livingroom tv"
  id: "Timerstop"
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.livingroom_tv
  action:
  - service: switch.turn_off
    target:
      entity_id: 
      - switch.tv

- alias: Media_Player restart timer TV Livingroom
  trigger:
    platform: state
    entity_id: binary_sensor.ping_livingroom_tv
    to: 'on'
  condition: 
  action:
  - service: timer.cancel
    target:
      entity_id: timer.livingroom_tv