######################################################################################################REDACTED
# @LeroybyREDACTED
# Original Repo : https://github.com/Leroyby/Homeassistant-ConfigREDACTED
# Automations Mediaplayer LivingroomREDACTED
######################################################################################################REDACTED
REDACTED
- alias: Media_Player start timer TV LivingroomREDACTED
  trigger:REDACTED
    platform: stateREDACTED
    entity_id: media_player.lg_webos_tv_a4abREDACTED
    to: 'off'REDACTED
  condition: REDACTED
  action:REDACTED
  - service: timer.startREDACTED
    target:REDACTED
      entity_id: timer.livingroom_tvREDACTED
REDACTED
- alias: "Timerstop tv livingroom"REDACTED
  id: "Timerstop"REDACTED
  trigger:REDACTED
  - platform: eventREDACTED
    event_type: timer.finishedREDACTED
    event_data:REDACTED
      entity_id: timer.livingroom_tvREDACTED
  action:REDACTED
  - service: switch.turn_offREDACTED
    target:REDACTED
      entity_id: REDACTED
      - switch.livingroom_tvREDACTED
REDACTED
- alias: Media_Player restart timer TV LivingroomREDACTED
  trigger:REDACTED
    platform: stateREDACTED
    entity_id: media_player.lg_webos_tv_a4abREDACTED
    to: 'on'REDACTED
  condition: REDACTED
  action:REDACTED
  - service: timer.cancelREDACTED
    target:REDACTED
      entity_id: timer.livingroom_tv