######################################################################################################
# @Leroyby
# Original Repo : https://github.com/Leroyby/Homeassistant-Config
# Automations Mediaplayer Livingroom
######################################################################################################

- alias: Media_Player start timer TV Livingroom
  trigger:
    platform: state
    entity_id: media_player.lg_webos_tv_a4ab
    to: 'off'
  condition: 
  action:
  - service: timer.start
    target:
      entity_id: timer.livingroom_tv

- alias: "Timerstop tv livingroom"
  id: "Timerstop"
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.livingroom_tv
  action:
  - service: switch.turn_off
    target:
      entity_id: 
      - switch.livingroom_tv

- alias: Media_Player restart timer TV Livingroom
  trigger:
    platform: state
    entity_id: media_player.lg_webos_tv_a4ab
    to: 'on'
  condition: 
  action:
  - service: timer.cancel
    target:
      entity_id: timer.livingroom_tv