######################################################################################################REDACTED
# @LeroybyREDACTED
# Original Repo : https://github.com/Leroyby/Homeassistant-ConfigREDACTED
# Automations Mediaplayer OfficeREDACTED
######################################################################################################REDACTED
- alias: media_player xbox trigger gaming modeREDACTED
  trigger:REDACTED
    platform: stateREDACTED
    entity_id: media_player.wohnzimmer_xboxREDACTED
    to: 'on'REDACTED
  condition:REDACTED
  action:REDACTED
  - service: automation.turn_onREDACTED
    entity_id: automation.gaming_mode_onREDACTED
  - service: light.turn_offREDACTED
    target:REDACTED
      entity_id: REDACTED
      - light.office_wiz_lights_ceilingREDACTED
  - service: input_boolean.turn_onREDACTED
    target:REDACTED
      entity_id: input_boolean.gaming_modeREDACTED
REDACTED
- alias: media_player xbox offREDACTED
  trigger:REDACTED
    platform: stateREDACTED
    entity_id: media_player.wohnzimmer_xboxREDACTED
    to: 'off'REDACTED
  condition:REDACTED
  action:REDACTED
  - service: input_boolean.turn_onREDACTED
    target:REDACTED
      entity_id: input_boolean.normal_modeREDACTED
  - service: timer.startREDACTED
    target:REDACTED
      entity_id: timer.office_xboxREDACTED
REDACTED
- alias: "Timerstop office xbox"REDACTED
  id: "Timerstop office xbox"REDACTED
  trigger:REDACTED
  - platform: eventREDACTED
    event_type: timer.finishedREDACTED
    event_data:REDACTED
      entity_id: timer.office_xboxREDACTED
  action:REDACTED
  - service: switch.turn_offREDACTED
    target:REDACTED
      entity_id: REDACTED
      - switch.office_xbox