######################################################################################################
# @Leroyby
# Original Repo : https://github.com/Leroyby/Homeassistant-Config
# Automations Mediaplayer Office
######################################################################################################
- alias: media_player xbox trigger gaming mode
  trigger:
    platform: state
    entity_id: media_player.wohnzimmer_xbox
    to: 'on'
  condition:
  action:
  - service: automation.turn_on
    entity_id: automation.gaming_mode_on
  - service: light.turn_off
    target:
      entity_id: 
      - light.office_wiz_lights_ceiling
  - service: input_boolean.turn_on
    target:
      entity_id: input_boolean.gaming_mode