settings:
  variables:
    entity_tablet: switch.galaxy_tab_a_screensaver
    entity_browser_mod: media_player.tablet

    translate_unknown: unbekannt
    translate_idle: Inaktiv
    translate_home: Zuhause
    translate_not_home: Nicht Zuhause
    translate_available: Verf체gbar
    translate_no_updates: Keine Updates
    translate_update_available: uppdatering tillg채nglig
    translate_updates_available: uppdateringar tillg채ngliga

    translate_off: aus
    translate_cool: Kalt
    translate_fan_only: Endast fl채kt
    translate_playing: playing
    translate_paused: pausiert
    translate_standby: standby
