######################################################################################################
# @Leroyby
# Original Repo : https://github.com/leroyby/Homeassistant-Config
# Lights group yaml file
######################################################################################################

- platform: group
  name: All_Lights 
  entities:
    - light.office_lights
    - light.bedroom_lights
    - light.Livingroom_lights
    - light.bad_klein
    
- platform: group
  name: bedroom_c_lights
  entities:
    - light.bedroom_c1
    - light.bedroom_c2
    - light.bedroom_c3

- platform: group
  name: bedroom_lights
  entities:
    - light.bedroom_c1
    - light.bedroom_c2
    - light.bedroom_c3
    - light.bedroom_light
    
- platform: group
  name: Livingroom_lights
  entities:
    - light.livingroom_sofa
    - light.livingroom_table
    - light.livingroom_tv_2
    - light.livingroom_c_lights

- platform: group
  name: Livingroom_c_lights
  unique_id: 2310232127
  entities:
    - light.livingroom_c_1_2
    - light.livingroom_c_6_1

- platform: group
  name: office_lights
  unique_id: 23101232058
  entities:
    - light.office_c1
    - light.office_c2
    - light.office_c3
    - light.office_desk

- platform: group
  name: office_c_lights
  unique_id: 23102731REDACTED
  entities:
    - light.office_c1
    - light.office_c2
    - light.office_c3
     


- platform: group
  name: Livingroom_motion_lights
  unique_id: 2210162058
  entities:
    - light.livingroom_sofa
    - light.livingroom_table

- platform: group
  name: toilet_Lights 
  entities:
    - light.bad_klein

