######################################################################################################REDACTED
# @LeroybyREDACTED
# Original Repo : https://github.com/leroyby/Homeassistant-ConfigREDACTED
# Lights group yaml fileREDACTED
######################################################################################################REDACTED
REDACTED
- platform: groupREDACTED
  name: All Lights REDACTED
  unique_id: 2210171730REDACTED
  entities:REDACTED
    - light.office_lightsREDACTED
    - light.bedroom_lightsREDACTED
    - light.Living_room_lightsREDACTED
    - light.bad_kleinREDACTED
    REDACTED
- platform: groupREDACTED
  name: Office_LightsREDACTED
  unique_id: 221006234REDACTED
  entities:REDACTED
    - light.wiz_office_REDACTED
    - light.wiz_office_REDACTED
    - light.wiz_office_REDACTED
    REDACTED
- platform: groupREDACTED
  name: bedroom_lightsREDACTED
  unique_id: 221006234REDACTED
  entities:REDACTED
    - light.decke_lREDACTED
    - light.decke_lREDACTED
    - light.decke_lREDACTED
    REDACTED
- platform: groupREDACTED
  name: Living_room_lightsREDACTED
  unique_id: 221006234REDACTED
  entities:REDACTED
    - light.livingroom_sofaREDACTED
    - light.livingroom_tableREDACTED
    - light.livingroom_tvREDACTED
REDACTED
- platform: groupREDACTED
  name: Living_room_motion_lightsREDACTED
  unique_id: 221016205REDACTED
  entities:REDACTED
    - light.livingroom_sofaREDACTED
    - light.livingroom_tableREDACTED
    - light.livingroom_motion_lightsREDACTED
REDACTED
- platform: groupREDACTED
  name: toilet_Lights REDACTED
  entities:REDACTED
    - light.bad_klein