######################################################################################################
# @Leroyby
# Original Repo : https://github.com/leroyby/Homeassistant-Config
# Lights group yaml file
######################################################################################################

- platform: group
  name: All_Lights 
  unique_id: 4e9c2053-a14d-474c-a83e-c5cafe164f78
  entities:
    - light.office_lights
    - light.bedroom_lights
    - light.Livingroom_lights

- platform: group
  name: bedroom_lights
  unique_id: 4e9c2053-a14d-474c-a83e-231028dd0109
  entities:
    - light.bedroom_c1
    - light.bedroom_c2
    - light.bedroom_c3
    - light.bedroom_light

- platform: group
  name: bedroom_lights2
  unique_id: 4e9c2053-a14d-474c-a83e-240506mi0100
  entities:
    - light.bedroom_c_lights
    - light.bedroom_light
     
- platform: group
  name: bedroom_c_lights
  unique_id: 4e9c2053-a14d-474c-a83e-231028dd0108
  entities:
    - light.bedroom_c1
    - light.bedroom_c2
    - light.bedroom_c3

- platform: group
  name: Livingroom_lights
  unique_id: 4e9c2053-a14d-474c-a83e-231028dd01REDACTED
  entities:
    - light.livingroom_sofa

- platform: group
  name: Livingroom_motion_lights
  unique_id: 4e9c2053-a14d-474c-a83e-231028dd0120
  entities:
    - light.livingroom_sofa

- platform: group
  name: Livingroom_c_lights
  unique_id: 4e9c2053-a14d-474c-a83e-231028dd0117
  entities:
    - light.livingroom_c_1_2
    - light.livingroom_c_6_1

- platform: group
  name: office_lights
  unique_id: 4e9c2053-a14d-474c-a83e-231028dd0118
  entities:
    - light.office_c_lights
    - light.office_desk

- platform: group
  name: office_c_lights
  unique_id: 4e9c2053-a14d-474c-a83e-231028dd0119
  entities:
    - light.office_c1
    - light.office_c2
    - light.office_c3

