######################################################################################################REDACTED
# @LeroybyREDACTED
# Original Repo : https://github.com/Leroyby/Homeassistant-ConfigREDACTED
# Count Sensors REDACTED
######################################################################################################REDACTED
- platform: templateREDACTED
  sensors:REDACTED
    count_automations:REDACTED
      icon_template: mdi:autorenewREDACTED
      value_template: "{{ states.automation | count }}"REDACTED
REDACTED
    count_scripts:REDACTED
      icon_template: mdi:script-text-outlineREDACTED
      value_template: "{{ states.script| count }}"REDACTED
REDACTED
    count_device_trackers:REDACTED
      icon_template: mdi:map-markerREDACTED
      value_template: "{{ states.device_tracker | count }}"REDACTED
REDACTED
    count_binary_sensors:REDACTED
      icon_template: mdi:unfold-more-horizontalREDACTED
      value_template: "{{ states.binary_sensor| count }}"REDACTED
REDACTED
    count_sensors:REDACTED
      icon_template: mdi:resistorREDACTED
      value_template: "{{ states.sensor | count }}"REDACTED
REDACTED
    count_switches:REDACTED
      icon_template: mdi:light-switchREDACTED
      value_template: "{{ states.switch | count }}"REDACTED
REDACTED
    count_zones:REDACTED
      icon_template: mdi:map-marker-radiusREDACTED
      value_template: "{{ states.zone | count }}"REDACTED
REDACTED
    count_input_booleans:REDACTED
      icon_template: mdi:toggle-switchREDACTED
      value_template: "{{ states.input_boolean | count }}"REDACTED
REDACTED
    count_input_numbers:REDACTED
      icon_template: mdi:numericREDACTED
      value_template: "{{ states.input_number | count }}"REDACTED
REDACTED
    count_input_texts:REDACTED
      icon_template: mdi:alphabeticalREDACTED
      value_template: "{{ states.input_text | count }}"REDACTED
REDACTED
    count_input_selects:REDACTED
      icon_template: mdi:view-listREDACTED
      value_template: "{{ states.input_select | count }}"REDACTED
REDACTED
    count_input_datetimes:REDACTED
      icon_template: mdi:calendar-clockREDACTED
      value_template: "{{ states.input_datetime | count }}"REDACTED
REDACTED
# Source: https://github.com/BeardedTinker/Home-Assistant_Config/blob/master/entities/sensors/system/count_lines.yamlREDACTED
REDACTED
- platform: command_lineREDACTED
  name: "Code line count"REDACTED
  command: " find /config/ -name '*.yaml' | xargs cat | wc -l"REDACTED
  scan_interval: 300