######################################################################################################
# @Leroyby
# Original Repo : https://github.com/Leroyby/Homeassistant-Config
# Energy Sensors 
######################################################################################################
- platform: integration
  source: sensor.total_energy_use
  name: Total Energy Use Over Time
  scan_interval: 120
  unit_time: h

- platform: statistics
  name: "Total Energy Use (Hourly Max)"
  entity_id: sensor.total_energy_use_hourly
  state_characteristic: value_max
  max_age:
    hours: 1
  sampling_size: 360

- platform: statistics
  name: "Total Energy Use (daily Max)"
  entity_id: sensor.total_energy_use_daily
  state_characteristic: value_max
  max_age:
    days: 1
  sampling_size: 360

- platform: statistics
  name: "Total Energy Use last hour"
  state_characteristic: mean
  entity_id: sensor.total_energy_use
  max_age:
    hours: 1

- platform: statistics
  name: "Total Energy Use last day"
  state_characteristic: mean
  entity_id: sensor.total_energy_use
  max_age:
    days: 1   

- platform: template
  sensors:
    total_energy_use:
      friendly_name: 'power total consumption'
      entity_id:
        - sensor.power_bedroom_tv
        - sensor.power_livingroom_cabinet
        - sensor.power_office_pc
        - sensor.power_office_xbox
      value_template: "{{ (states('sensor.power_bedroom_tv')|float + states('sensor.power_livingroom_cabinet')|float + states('sensor.power_office_pc')|float+ states('sensor.power_office_xbox')|float)|round(3) }}"
      unit_of_measurement: "W"

- platform: integration
  source: sensor.total_energy_use
  name: Total Energy Spend
  unit_prefix: k
  round: 2
