######################################################################################################REDACTED
# @LeroybyREDACTED
# Original Repo : https://github.com/Leroyby/Homeassistant-ConfigREDACTED
# Energy Sensors REDACTED
######################################################################################################REDACTED
- platform: integrationREDACTED
  source: sensor.total_energy_useREDACTED
  name: Total Energy Use Over TimeREDACTED
  scan_interval: 120REDACTED
  unit_time: hREDACTED
REDACTED
- platform: statisticsREDACTED
  name: "Total Energy Use (Hourly Max)"REDACTED
  entity_id: sensor.total_energy_use_hourlyREDACTED
  state_characteristic: value_maxREDACTED
  max_age:REDACTED
    hours: REDACTED
  sampling_size: 20REDACTED
REDACTED
- platform: statisticsREDACTED
  name: "Total Energy Use (daily Max)"REDACTED
  entity_id: sensor.total_energy_use_dailyREDACTED
  state_characteristic: value_maxREDACTED
  max_age:REDACTED
    days: REDACTED
  sampling_size: REDACTED
REDACTED
- platform: statisticsREDACTED
  name: "Total Energy Use last hour"REDACTED
  state_characteristic: meanREDACTED
  entity_id: sensor.total_energy_useREDACTED
  max_age:REDACTED
    hours: REDACTED
  sampling_size: 360REDACTED
REDACTED
- platform: statisticsREDACTED
  name: "Total Energy Use daily"REDACTED
  state_characteristic: totalREDACTED
  entity_id: sensor.total_energy_useREDACTED
  max_age:REDACTED
    days: 1   REDACTED
  sampling_size: 2500REDACTED
REDACTED
- platform: templateREDACTED
  sensors:REDACTED
    total_energy_use:REDACTED
      friendly_name: 'power total consumption'REDACTED
      entity_id:REDACTED
        - sensor.power_bedroom_tvREDACTED
        - sensor.power_livingroom_cabinetREDACTED
        - sensor.power_office_pcREDACTED
        - sensor.power_office_xboxREDACTED
      value_template: "{{ (states('sensor.power_bedroom_tv')|float + states('sensor.power_livingroom_cabinet')|float + states('sensor.power_office_pc')|float+ states('sensor.power_office_xbox')|float)|round(3) }}"REDACTED
      unit_of_measurement: "W"REDACTED
REDACTED
- platform: integrationREDACTED
  source: sensor.total_energy_useREDACTED
  name: Total Energy SpendREDACTED
  unit_prefix: kREDACTED
  round: REDACTED
