######################################################################################################
# @Leroyby
# Original Repo : https://github.com/Leroyby/Homeassistant-Config
# TEST SENSOR SSB Information
######################################################################################################
sensor:
  - platform: swiss_public_transport
    name: test SBB
    from: 000000022
    to: 000000025