######################################################################################################REDACTED
# @LeroybyREDACTED
# Original Repo : https://github.com/Leroyby/Homeassistant-ConfigREDACTED
# Various SensorsREDACTED
######################################################################################################REDACTED
- platform: templateREDACTED
  sensors:REDACTED
    sun_elevation:REDACTED
      friendly_name: "Sun Elevation"REDACTED
      unit_of_measurement: '°'REDACTED
      value_template: "{{ state_attr('sun.sun', 'elevation') }}"REDACTED
