######################################################################################################REDACTED
# @LeroybyREDACTED
# Original Repo : https://github.com/Leroyby/Homeassistant-ConfigREDACTED
# binary sensors activityREDACTED
######################################################################################################REDACTED
- platform: templateREDACTED
  sensors:REDACTED
    activity_in_livingroom_cabinet:REDACTED
      friendly_name: Activity in the living room cabinetREDACTED
      value_template: >REDACTED
        {{ is_state("binary_sensor.motion_livingroom_cabinet_occupancy", "on")REDACTED
            or is_state("binary_sensor.livingroom_cabinet_on", "on")REDACTED
            }}REDACTED
      delay_off: "00:03:00"