######################################################################################################
# @Leroyby
# Original Repo : https://github.com/Leroyby/Homeassistant-Config
# binary sensors activity
######################################################################################################
- platform: template
  sensors:
    activity_in_livingroom_cabinet:
      friendly_name: Activity in the living room cabinet
      value_template: >
        {{ is_state("binary_sensor.motion_livingroom_cabinet_occupancy", "on")
            or is_state("binary_sensor.livingroom_icemachine_on", "on")
            }}
      delay_off: "00:01:00"

    activity_on_dining_table:
      friendly_name: Activity on the dining table
      value_template: >
        {{ is_state("sensor.Vibration_office_1_action", "on")
           }}
      delay_off: "00:05:00"