######################################################################################################
# @Leroyby
# Original Repo : https://github.com/Leroyby/Homeassistant-Config
# binary sensors activity
######################################################################################################
- platform: template
  sensors:
    activity_in_livingroom_cabinet:
      friendly_name: Activity in the living room cabinet
      value_template: >
        {{ is_state("binary_sensor.contact_livingroom_cabinet_contact", "on")
            or is_state("binary_sensor.livingroom_icemachine_on", "on")
            }}
      delay_off: "00:01:00"

    activity_in_bedroom:
      friendly_name: Activity in the bedroom
      value_template: >
        {{ is_state("binary_sensor.bedroom_tv_on", "on") }}
      delay_off: "00:01:00"

    activity_on_dining_table:
      friendly_name: Activity on the dining table
      value_template: >
        {{ is_state("sensor.Vibration_office_1_action", "on") }}
      delay_off: "00:05:00"

    activity_in_office:
      friendly_name: Activity in the office
      value_template: >
        {{ is_state("binary_sensor.office_pc_on", "on")
            or is_state("binary_sensor.motion_in_office", "on") 
        }}
      delay_off: "00:03:00"

    activity_in_hall:
      friendly_name: Activity in hall
      value_template: >
        {{ is_state("binary_sensor.motion_hall_occupancy", "on")
        }}
      delay_off: "00:01:00"

    activity_in_livingroom:
      friendly_name: Activity in the living room
      value_template: >
        {{ is_state("binary_sensor.motion_in_livingroom", "on")
            or is_state("binary_sensor.vibration_1", "on")
            or is_state("binary_sensor.activity_in_livingroom_cabinet", "on")
            }}
      delay_off: "00:03:00"

    activity_in_kitchen:
      friendly_name: Activity in the kitchen
      value_template: >
        {{ is_state("binary_sensor.motion_livingroom_occupancy", "on") }}
      delay_off: "00:01:00"

    no_one_home:
      friendly_name: No one is home
      value_template: >
        {{ not is_state("person.leroy", "home")
            }}    