######################################################################################################
# @Leroyby
# Original Repo : https://github.com/Leroyby/Homeassistant-Config
# binary sensors activity
######################################################################################################
- platform: template
  sensors:
    activity_in_livingroom_cabinet:
      friendly_name: Activity in the living room cabinet
      value_template: >
        {{ is_state("binary_sensor.motion_livingroom_cabinet_occupancy", "on")
            or is_state("binary_sensor.livingroom_cabinet_on", "on")
            }}
      delay_off: "00:03:00"