######################################################################################################
# @Leroyby
# Original Repo : https://github.com/Leroyby/Homeassistant-Config
# binary sensors
######################################################################################################
- platform: template
  sensors:
    motion_detected:
      friendly_name: Any motion detected
      value_template: >
        {{ is_state("binary_sensor.activity_in_kitchen", "on")
            or is_state("binary_sensor.activity_in_livingroom", "on")
            or is_state("binary_sensor.activity_in_office", "on")
            or is_state("binary_sensor.activity_in_bedroom", "on") }}
            
    motion_detected_in_last_hour:
      friendly_name: Any motion detected in last hour
      value_template: >
        {{ is_state("binary_sensor.motion_detected", "on") }}
      delay_off: "01:00:00"

    someone_in_the_house_in_last_hour:
      friendly_name: Someone in the house in the last hour
      value_template: >
        {{ is_state("binary_sensor.motion_detected_in_last_hour", "on") }}
      delay_off: "01:00:00"

    activity_in_livingroom:
      friendly_name: Activity in the living room
      value_template: >
        {{ is_state("binary_sensor.motion_livingroom_occupancy", "on")
            or is_state("media_player.lg_webos_smart_tv", "on") }}
      delay_off: "00:03:00"

    activity_in_kitchen:
      friendly_name: Activity in the kitchen
      value_template: >
        {{ is_state("binary_sensor.motion_livingroom_occupancy", "on") }}
      delay_off: "00:01:00"

    activity_in_office:
      friendly_name: Activity in the office
      value_template: >
        {{ is_state("media_player.wohnzimmer_xbox", "on")
            or is_state("binary_sensor.motion_office_occupancy", "on") 
            or is_state("binary_sensor.office_pc_on", "on")
            }}
      delay_off: "00:01:00"

    activity_in_bedroom:
      friendly_name: Activity in the bedroom
      value_template: >
        {{ is_state("switch.bedroom_tv", "on")
            or is_state("light.bedroom_lights", "on")
           }}
      delay_off: "00:01:00"

    activity_on_dining_table:
      friendly_name: Activity on the dining table
      value_template: >
        {{ is_state("sensor.Vibration_office_1_action", "on")
           }}
      delay_off: "00:05:00"

    any_light_on:
      friendly_name: Any light is on
      value_template: >
        {% set office_lights_on = is_state("light.office_lights", "on") %}
        {% set bedroom_lights_on = is_state("light.bedroom_lights", "on") %}
        {% set living_room_lights_on = is_state("light.livingroom_lights", "on") %}
        {{ office_lights_on or bedroom_lights_on or living_room_lights_on }}

    office_pc_on:
      friendly_name: office pc is on
      value_template: "{{ states('sensor.power_office_pc')|float > 50.0 }}"
      delay_off: "00:01:00"

    any_media_player_on:
      friendly_name: Any media player is on
      value_template: >
        {% set office_media_player_on = is_state("media_player.lbxbox", "on") %}
        {% set bedroom_media_player_on = is_state("", "on") %}
        {% set living_room_media_player_on = is_state("media_player.lg_webos_tv_a4ab", "on") %}
        {{ office_media_player_on or bedroom_media_player_on or living_room_media_player_on }}

    anything_on:
      friendly_name: Anything is on
      value_template: >
        {% set light_on = is_state("binary_sensor.any_light_on", "on") %}
        {% set media_player_on = is_state("binary_sensor.any_media_player_on", "on") %}
        {{ light_on or media_player_on }}
  
    no_one_home:
      friendly_name: No one is home
      value_template: >
        {{ not is_state("person.leroy", "home")
            and not is_state("person.USER2", "home") }}

- platform: workday
  country: CH
  workdays: [mon, tue, wed, thu, fri]
  excludes: [sat, sun]

