######################################################################################################REDACTED
# @LeroybyREDACTED
# Original Repo : https://github.com/Leroyby/Homeassistant-ConfigREDACTED
# binary sensorsREDACTED
######################################################################################################REDACTED
- platform: templateREDACTED
  sensors:REDACTED
    motion_detected:REDACTED
      friendly_name: Any motion detectedREDACTED
      value_template: >REDACTED
        {{ is_state("binary_sensor.activity_in_kitchen", "on")REDACTED
            or is_state("binary_sensor.activity_in_livingroom", "on")REDACTED
            or is_state("binary_sensor.activity_in_office", "on")REDACTED
            or is_state("binary_sensor.activity_in_bedroom", "on") }}REDACTED
            REDACTED
    motion_detected_in_last_hour:REDACTED
      friendly_name: Any motion detected in last hourREDACTED
      value_template: >REDACTED
        {{ is_state("binary_sensor.motion_detected", "on") }}REDACTED
      delay_off: "01:00:00"REDACTED
REDACTED
    someone_in_the_house_in_last_hour:REDACTED
      friendly_name: Someone in the house in the last hourREDACTED
      value_template: >REDACTED
        {{ is_state("binary_sensor.motion_detected_in_last_hour", "on") }}REDACTED
      delay_off: "01:00:00"REDACTED
REDACTED
    activity_in_livingroom:REDACTED
      friendly_name: Activity in the living roomREDACTED
      value_template: >REDACTED
        {{ is_state("binary_sensor.motion_livingroom_occupancy", "on")REDACTED
            or is_state("media_player.lg_webos_smart_tv", "on")REDACTED
            or is_state("binary_sensor.contact_livingroom_cabinet_contact", "on") }}REDACTED
      delay_off: "00:03:00"REDACTED
REDACTED
    activity_in_kitchen:REDACTED
      friendly_name: Activity in the kitchenREDACTED
      value_template: >REDACTED
        {{ is_state("binary_sensor.motion_livingroom_occupancy", "on") }}REDACTED
      delay_off: "00:01:00"REDACTED
REDACTED
    activity_in_office:REDACTED
      friendly_name: Activity in the officeREDACTED
      value_template: >REDACTED
        {{ is_state("media_player.wohnzimmer_xbox", "on")REDACTED
            or is_state("binary_sensor.motion_office_occupancy", "on") REDACTED
            or is_state("binary_sensor.office_pc_on", "on")REDACTED
            }}REDACTED
      delay_off: "00:01:00"REDACTED
REDACTED
    activity_in_bedroom:REDACTED
      friendly_name: Activity in the bedroomREDACTED
      value_template: >REDACTED
        {{ is_state("switch.bedroom_tv", "on")REDACTED
            or is_state("light.bedroom_lights", "on")REDACTED
           }}REDACTED
      delay_off: "00:01:00"REDACTED
REDACTED
    activity_on_dining_table:REDACTED
      friendly_name: Activity on the dining tableREDACTED
      value_template: >REDACTED
        {{ is_state("sensor.Vibration_office_1_action", "on")REDACTED
           }}REDACTED
      delay_off: "00:05:00"REDACTED
REDACTED
    any_light_on:REDACTED
      friendly_name: Any light is onREDACTED
      value_template: >REDACTED
        {% set office_lights_on = is_state("light.office_lights", "on") %}REDACTED
        {% set bedroom_lights_on = is_state("light.bedroom_lights", "on") %}REDACTED
        {% set living_room_lights_on = is_state("light.livingroom_lights", "on") %}REDACTED
        {{ office_lights_on or bedroom_lights_on or living_room_lights_on }}REDACTED
REDACTED
    office_pc_on:REDACTED
      friendly_name: office pc is onREDACTED
      value_template: "{{ states('sensor.power_office_pc')|float > 50.0 }}"REDACTED
      delay_off: "00:01:00"REDACTED
REDACTED
    livingroom_cabinet_on:REDACTED
      friendly_name: livingroom cabinet is onREDACTED
      value_template: "{{ states('sensor.power_livingroom_cabinet')|float > 10.0 }}"REDACTED
      delay_off: "00:01:00"REDACTED
REDACTED
REDACTED
    any_media_player_on:REDACTED
      friendly_name: Any media player is onREDACTED
      value_template: >REDACTED
        {% set office_media_player_on = is_state("media_player.lbxbox", "on") %}REDACTED
        {% set bedroom_media_player_on = is_state("binary_sensor.ping_bedroom_tv", "on") %}REDACTED
        {% set living_room_media_player_on = is_state("media_player.lg_webos_tv_a4ab", "on") %}REDACTED
        {{ office_media_player_on or bedroom_media_player_on or living_room_media_player_on }}REDACTED
REDACTED
    any_switch_on:REDACTED
      friendly_name: Any switch is onREDACTED
      value_template: >REDACTED
        {% set sw1 = is_state("", "on") %}REDACTED
        {% set sw2 = is_state("", "on") %}REDACTED
        {% set sw3 = is_state("", "on") %}REDACTED
        {% set sw4 = is_state("", "on") %}REDACTED
        {{ sw1 or sw2 or sw3 or sw4 }}REDACTED
REDACTED
    anything_on:REDACTED
      friendly_name: Anything is onREDACTED
      value_template: >REDACTED
        {% set light_on = is_state("binary_sensor.any_light_on", "on") %}REDACTED
        {% set media_player_on = is_state("binary_sensor.any_media_player_on", "on") %}REDACTED
        {{ light_on or media_player_on }}REDACTED
  REDACTED
    no_one_home:REDACTED
      friendly_name: No one is homeREDACTED
      value_template: >REDACTED
        {{ not is_state("person.leroy", "home")REDACTED
            and not is_state("person.USER2", "home") REDACTED
            and not is_state("media_player.lbxbox", "on")}}REDACTED
REDACTED
- platform: workdayREDACTED
  country: CHREDACTED
  workdays: [mon, tue, wed, thu, fri]REDACTED
  excludes: [sat, sun]REDACTED
REDACTED
