######################################################################################################
# @Leroyby
# Original Repo : https://github.com/Leroyby/Homeassistant-Config
# binary sensors
######################################################################################################
- platform: template
  sensors:
    motion_detected:
      friendly_name: Any motion detected
      value_template: >
        {{ is_state("binary_sensor.activity_in_kitchen", "on")
            or is_state("binary_sensor.activity_in_livingroom", "on")
            or is_state("binary_sensor.activity_in_office", "on")
            or is_state("binary_sensor.activity_in_hall", "on")
            or is_state("binary_sensor.activity_in_bedroom", "on") }}
            
    motion_detected_in_last_hour:
      friendly_name: Any motion detected in last hour
      value_template: >
        {{ is_state("binary_sensor.motion_detected", "on") }}
      delay_off: "01:00:00"

    motion_in_office:
      friendly_name: motion in the office
      value_template: >
        {{ is_state("binary_sensor.motion_office_occupancy", "on") 
            }}
      delay_off: "00:03:00"

    motion_in_livingroom:
      friendly_name: motion in the living room
      value_template: >
        {{ is_state("binary_sensor.motion_livingroom_occupancy", "on") 
            }}
      delay_off: "00:03:00"


    someone_in_the_house_in_last_hour:
      friendly_name: Someone in the house in the last hour
      value_template: >
        {{ is_state("binary_sensor.motion_detected_in_last_hour", "on") }}
      delay_off: "01:00:00"

    any_light_on:
      friendly_name: Any light is on
      value_template: >
        {% set office_lights_on = is_state("light.office_lights", "on") %}
        {% set bedroom_lights_on = is_state("light.bedroom_lights", "on") %}
        {% set living_room_lights_on = is_state("light.livingroom_lights", "on") %}
        {{ office_lights_on or bedroom_lights_on or living_room_lights_on }}

    office_pc_on:
      friendly_name: Office PC is on
      value_template: "{{ states('sensor.power_office_pc')|float > 50.0 }}"
      delay_off: "00:01:00"

    xbox_on:
      friendly_name: Office Xbox is on
      value_template: "{{ states('sensor.power_office_pc')|float > 30.0 }}"
      delay_off: "00:01:00"

    bedroom_tv_on:
      friendly_name: Bedroom TV on
      value_template: "{{ states('sensor.power_bedroom_tv')|float > 30.0 }}"
      delay_off: "00:01:00"

    livingroom_icemachine_on:
      friendly_name: Icemachine is on
      value_template: "{{ states('sensor.power_livingroom_cabinet')|float > 50.0 }}"
      delay_off: "00:45:00"

    bedroom_tv_on:
      friendly_name: bedroom tv is on
      value_template: "{{ states('sensor.power_bedroom_tv')|float > 24.5 }}"
      delay_off: "00:15:00"

    livingroom_cabinet_on:
      friendly_name: livingroom cabinet is on
      value_template: "{{ states('sensor.power_livingroom_cabinet')|float > 10.0 }}"
      delay_off: "00:01:00"


    any_media_player_on:
      friendly_name: Any media player is on
      value_template: >
        {% set office_media_player_on = is_state("binary:_sensor.xbox_on", "on") %}
        {% set bedroom_media_player_on = is_state("binary_sensor.ping_bedroom_tv", "on") %}
        {% set living_room_media_player_on = is_state("media_player.lg_webos_tv_a4ab", "on") %}
        {{ office_media_player_on or bedroom_media_player_on or living_room_media_player_on }}

    any_switch_on:
      friendly_name: Any switch is on
      value_template: >
        {% set sw1 = is_state("", "on") %}
        {% set sw2 = is_state("", "on") %}
        {% set sw3 = is_state("", "on") %}
        {% set sw4 = is_state("", "on") %}
        {{ sw1 or sw2 or sw3 or sw4 }}

    anything_on:
      friendly_name: Anything is on
      value_template: >
        {% set light_on = is_state("binary_sensor.any_light_on", "on") %}
        {% set media_player_on = is_state("binary_sensor.any_media_player_on", "on") %}
        {{ light_on or media_player_on }}

