######################################################################################################REDACTED
# @LeroybyREDACTED
# Original Repo : https://github.com/Leroyby/Homeassistant-ConfigREDACTED
# binary sensors pingREDACTED
######################################################################################################REDACTED
- platform: pingREDACTED
  host: 192.168.178.REDACTED
  name: "ping modem"REDACTED
  count: REDACTED
  scan_interval: 30REDACTED
REDACTED
- platform: pingREDACTED
  host: 1.1.1.REDACTED
  name: "ping cloudflare"REDACTED
  count: REDACTED
  scan_interval: 30REDACTED
REDACTED
- platform: pingREDACTED
  host: 8.8.8.REDACTED
  name: "ping google"REDACTED
  count: REDACTED
  scan_interval: 30REDACTED
REDACTED
- platform: pingREDACTED
  host: ubnt.leroyby.chREDACTED
  name: "ping my website"REDACTED
  count: REDACTED
  scan_interval: 30REDACTED
REDACTED
- platform: pingREDACTED
  host: 192.168.178.REDACTED
  name: "ping modem"REDACTED
  count: REDACTED
  scan_interval: 30REDACTED
REDACTED
- platform: pingREDACTED
  host: 192.168.178.REDACTED
  name: "ping router"REDACTED
  count: REDACTED
  scan_interval: 30REDACTED
REDACTED
- platform: pingREDACTED
  host: 192.168.178.1REDACTED
  name: "ping switch"REDACTED
  count: REDACTED
  scan_interval: 30REDACTED
REDACTED
- platform: pingREDACTED
  host: 192.168.178.1REDACTED
  name: "ping ap"REDACTED
  count: REDACTED
  scan_interval: 30REDACTED
REDACTED
- platform: pingREDACTED
  host: 192.168.178.10REDACTED
  name: "ping bedroom tv"REDACTED
  count: REDACTED
  scan_interval: 30  REDACTED
REDACTED
