######################################################################################################REDACTED
# @LeroybyREDACTED
# Original Repo : https://github.com/Leroyby/Homeassistant-ConfigREDACTED
# binary sensors pingREDACTED
######################################################################################################REDACTED
- platform: pingREDACTED
  host: 192.168.178.1REDACTED
  name: "ping modem"REDACTED
  count: 2REDACTED
  scan_interval: 30REDACTED
REDACTED
- platform: pingREDACTED
  host: 1.1.1.1REDACTED
  name: "ping cloudflare"REDACTED
  count: 2REDACTED
  scan_interval: 30REDACTED
REDACTED
- platform: pingREDACTED
  host: 8.8.8.8REDACTED
  name: "ping google"REDACTED
  count: 2REDACTED
  scan_interval: 30REDACTED
REDACTED
- platform: pingREDACTED
  host: REDACTED
  name: "ping my website"REDACTED
  count: 2REDACTED
  scan_interval: 30REDACTED
REDACTED
- platform: pingREDACTED
  host: 192.168.178.1REDACTED
  name: "ping modem"REDACTED
  count: 2REDACTED
  scan_interval: 30REDACTED
REDACTED
- platform: pingREDACTED
  host: 192.168.178.1REDACTED
  name: "ping router"REDACTED
  count: 2REDACTED
  scan_interval: 30REDACTED
REDACTED
- platform: pingREDACTED
  host: 192.168.178.15REDACTED
  name: "ping switch"REDACTED
  count: 2REDACTED
  scan_interval: 30REDACTED
REDACTED
- platform: pingREDACTED
  host: 192.168.178.16REDACTED
  name: "ping ap"REDACTED
  count: 2REDACTED
  scan_interval: 30REDACTED
REDACTED
- platform: pingREDACTED
  host: 192.168.178.101REDACTED
  name: "ping livingroom tv"REDACTED
  count: 2REDACTED
  scan_interval: 60REDACTED
REDACTED
- platform: pingREDACTED
  host: 192.168.178.102REDACTED
  name: "ping bedroom tv"REDACTED
  count: 2REDACTED
  scan_interval: 60REDACTED
REDACTED
REDACTED
REDACTED
