######################################################################################################REDACTED
# @LeroybyREDACTED
# Original Repo : https://github.com/Leroyby/Homeassistant-ConfigREDACTED
# Automations Lights BedroomREDACTED
######################################################################################################REDACTED
REDACTED
- alias: Light bedroom off nightREDACTED
  trigger:REDACTED
    platform: stateREDACTED
    entity_id: sensor.iphone_von_leroy_battery_stateREDACTED
    to: 'Charging'REDACTED
  condition: REDACTED
    condition: timeREDACTED
    after: "21:30:00"REDACTED
    before: "04:00:00"REDACTED
  action:REDACTED
  - service: light.turn_offREDACTED
    target:REDACTED
      entity_id: REDACTED
      - light.bedroom_lightsREDACTED
    data:REDACTED
      transition: 7REDACTED
REDACTED
- alias: Light bedroom off tv timeREDACTED
  trigger:REDACTED
    platform: stateREDACTED
    entity_id: binary_sensor.ping_bedroom_tvREDACTED
    to: 'on'REDACTED
  condition: REDACTED
  action:REDACTED
  - service: light.turn_offREDACTED
    target:REDACTED
      entity_id: REDACTED
      - light.bedroom_lightsREDACTED
    data:REDACTED
      transition: 5  REDACTED
