######################################################################################################
# @Leroyby
# Original Repo : https://github.com/Leroyby/Homeassistant-Config
# Automations Lights Bedroom
######################################################################################################

- alias: Light bedroom off night
  trigger:
    platform: state
    entity_id: sensor.iphone_von_leroy_battery_state
    to: 'Charging'
  condition: 
    condition: time
    after: "21:30:00"
    before: "04:00:00"
  action:
  - service: light.turn_off
    target:
      entity_id: 
      - light.bedroom_lights
    data:
      transition: 7

- alias: Light bedroom off tv time
  trigger:
    platform: state
    entity_id: binary_sensor.ping_bedroom_tv
    to: 'on'
  condition: 
  action:
  - service: light.turn_off
    target:
      entity_id: 
      - light.bedroom_lights
    data:
      transition: 5  

- alias: Light bedroom off night windows open
  trigger:
    - platform: state
      entity_id: binary_sensor.contact_bedroom_window_contact
      to: "on"
  condition:
  - condition: state
    entity_id: sun.sun
    state: "below_horizon"
  action:
    - service: climate.set_hvac_mode
      target:
        entity_id: climate.bedroom_thermostat
      data:
        hvac_mode: "off"
