######################################################################################################
# @USER1by
# Original Repo : https://github.com/USER1by/Homeassistant-Config
# Automation Lights Bedroom
######################################################################################################

- alias: Bedroom Button Lights turn on
  trigger:
    platform: state
    entity_id: sensor.button_bedroom_action
    to: 'on' 
  condition:
    condition: state
    entity_id: light.bedroom_lights
    state: 'off'
  action:
    service: light.turn_on
    data:
      entity_id: light.bedroom_lights
      brightness_pct: 25

- alias: Bedroom Button Lights turn off
  trigger:
    platform: state
    entity_id: sensor.button_bedroom_action
    to: 'on' 
  condition:
    condition: state
    entity_id: light.bedroom_lights
    state: 'on'
  action:
    service: light.turn_off
    data:
      entity_id: light.bedroom_lights