######################################################################################################
# @Leroyby
# Original Repo : https://github.com/Leroyby/Homeassistant-Config
# Automations Lights Bedroom
######################################################################################################

- alias: Light bedroom off night
  trigger:
    platform: state
    entity_id: sensor.iphone_von_leroy_battery_state
    to: 'Charging'
  condition: 
    condition: time
    after: "21:30:00"
    before: "04:00:00"
  action:
  - service: light.turn_off
    target:
      entity_id: 
      - light.bedroom_lights
    data:
      transition: 7

- alias: Light bedroom off tv time
  trigger:
    platform: state
    entity_id: binary_sensor.ping_bedroom_tv
    to: 'on'
  condition: 
  action:
  - service: light.turn_off
    target:
      entity_id: 
      - light.bedroom_lights
    data:
      transition: 5


- alias: Bedroom Warm White Light
  description: ''
  trigger: []
  condition: []
  action:
  - parallel:
    - service: light.turn_on
      data:
        kelvin: 2000
      target:
        entity_id: light.bedroom_c_light
    - service: light.turn_on
      data:
        kelvin: 2000
      target:
        entity_id: light.bedroom_light
  - service: input_select.select_option
    data:
      option: automation.Bedroom Warm White Light
    target:
      entity_id: input_select.last_light_bedroom
  mode: single

- alias: Bedroom Cold White Light
  description: ''
  trigger: []
  condition: []
  action:
  - parallel:
    - service: light.turn_on
      data:
        kelvin: 6000
      target:
        entity_id: light.bedroom_c_light
    - service: light.turn_on
      data:
        kelvin: 6000
      target:
        entity_id: light.bedroom_light
  - service: input_select.select_option
    data:
      option: automation.Bedroom Cold White Light
    target:
      entity_id: input_select.last_light_bedroom
  mode: single

- alias: Bedroom White Light
  description: ''
  trigger: []
  condition: []
  action:
  - parallel:
    - service: light.turn_on
      data:
        kelvin: 3000
      target:
        entity_id: light.bedroom_c_light
    - service: light.turn_on
      data:
        kelvin: 3000
      target:
        entity_id: light.bedroom_light
  - service: input_select.select_option
    data:
      option: automation.Bedroom White Light
    target:
      entity_id: input_select.last_light_bedroom
  mode: single
