######################################################################################################REDACTED
# @LeroybyREDACTED
# Original Repo : https://github.com/Leroyby/Homeassistant-ConfigREDACTED
# Automation Lights LivingroomREDACTED
######################################################################################################REDACTED
- alias: Light Livingroom Floor Off during TVREDACTED
  trigger:REDACTED
    platform: stateREDACTED
    entity_id: binary_sensor.ping_livingroom_tvREDACTED
    to: 'on'REDACTED
  condition:REDACTED
  action:REDACTED
  - service: light.turn_offREDACTED
    target:REDACTED
      entity_id: REDACTED
      - light.livingroom_tv   REDACTED
      - light.light_treeREDACTED
REDACTED
- alias: Light Livingroom off after MotionREDACTED
  trigger:REDACTED
    platform: stateREDACTED
    entity_id: binary_sensor.activity_in_livingroomREDACTED
    to: 'off'REDACTED
  condition: REDACTED
  - condition: stateREDACTED
    entity_id: input_boolean.morning_lights_livingroomREDACTED
    state: "off"REDACTED
  action:REDACTED
  - service: light.turn_offREDACTED
    target:REDACTED
      entity_id: REDACTED
      - light.livingroom_motion_lightsREDACTED
REDACTED
- alias: Light Livingroom on after MotionREDACTED
  trigger:REDACTED
    platform: stateREDACTED
    entity_id: binary_sensor.activity_in_livingroomREDACTED
    to: 'on'REDACTED
  condition:REDACTED
  - condition: stateREDACTED
    entity_id: sun.sunREDACTED
    state: "below_horizon"REDACTED
  - condition: stateREDACTED
    entity_id: binary_sensor.activity_in_livingroomREDACTED
    state: 'off'    REDACTED
  action:REDACTED
  - service: light.turn_onREDACTED
    target:REDACTED
      entity_id: REDACTED
      - light.livingroom_motion_lightsREDACTED
REDACTED
REDACTED
#- alias: Light Livingroom Tree onREDACTED
#  trigger:REDACTED
#    platform: time_patternREDACTED
#    minutes: /8REDACTED
#  condition:REDACTED
#  - condition: stateREDACTED
#    entity_id: sun.sunREDACTED
#    state: "below_horizon"REDACTED
#  - condition: stateREDACTED
#    entity_id: binary_sensor.ping_livingroom_tvREDACTED
#    state: "off"REDACTED
#  - condition: stateREDACTED
#    entity_id: binary_sensor.activity_in_livingroomREDACTED
#    state: "on"    REDACTED
#  action:REDACTED
#  - service: light.turn_onREDACTED
#    target:REDACTED
#      entity_id: REDACTED
#      - light.light_treeREDACTED
REDACTED
