######################################################################################################
# @Leroyby
# Original Repo : https://github.com/Leroyby/Homeassistant-Config
# Automation Lights Livingroom
######################################################################################################
- alias: Light Livingroom Floor Off during TV
  trigger:
    platform: state
    entity_id: binary_sensor.ping_livingroom_tv
    to: 'on'
  condition:
  action:
  - service: light.turn_off
    target:
      entity_id: 
      - light.livingroom_tv   

- alias: Light Livingroom off after Motion
  trigger:
    platform: state
    entity_id: binary_sensor.activity_in_livingroom
    to: 'off'
  condition: 
  - condition: state
    entity_id: input_boolean.morning_lights_livingroom
    state: "off"
  action:
  - service: light.turn_off
    target:
      entity_id: 
      - light.livingroom_motion_lights

- alias: Light Livingroom on after Motion
  trigger:
    platform: state
    entity_id: binary_sensor.activity_in_livingroom
    to: 'on'
  condition:
  - condition: state
    entity_id: sun.sun
    state: "below_horizon"  
  action:
  - service: light.turn_on
    target:
      entity_id: 
      - light.livingroom_motion_lights
