######################################################################################################
# @Leroyby
# Original Repo : https://github.com/Leroyby/Homeassistant-Config
# Automation Lights Livingroom
######################################################################################################

- alias: Light Livingroom off after Motion
  trigger:
    platform: state
    entity_id: binary_sensor.motion_in_livingroom
    to: 'off'
  condition: 
  action:
  - service: light.turn_off
    target:
      entity_id: 
      - light.livingroom_motion_lights

- alias: Light Livingroom on after Motion
  trigger:
    platform: state
    entity_id: binary_sensor.motion_in_livingroom
    to: 'on'
  condition:
  - condition: state
    entity_id: sun.sun
    state: "below_horizon"
  - condition: state
    entity_id: switch.tv
    state: "off"
  action:
  - service: light.turn_on
    target:
      entity_id: 
      - light.livingroom_motion_lights
  - service: timer.start
    target:
      entity_id: timer.livingroom_lights_motion

- alias: "Timerstop livingroom lights motion"
  id: "Timerstop livingroom lights motion"
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.livingroom_lights_motion
  action:
  - service: light.turn_off
    target:
      entity_id: 
      - light.livingroom_motion_lights      

- alias: Lights restart livingroom lights motion timer
  trigger:
    platform: state
    entity_id: binary_sensor.motion_in_livingroom
    to: 'on'
  condition: 
  action:
  - service: timer.cancel
    target:
      entity_id: timer.livingroom_lights_motion 
