######################################################################################################
# @USER1by
# Original Repo : https://github.com/USER1by/Homeassistant-Config
# Office Lights Office
######################################################################################################

- alias: Office Button Lights 
  trigger:
    platform: state
    entity_id: sensor.aqara_button_office_action
    to: 'single' 
  condition: []
  action:
    service: light.toggle
    entity_id: light.office_lights