######################################################################################################REDACTED
# @LeroybyREDACTED
# Original Repo : https://github.com/Leroyby/Homeassistant-ConfigREDACTED
# Automations Office LightsREDACTED
######################################################################################################REDACTED
REDACTED
- alias: Light Office off after MotionREDACTED
  trigger:REDACTED
    platform: stateREDACTED
    entity_id: binary_sensor.activity_in_officeREDACTED
    to: 'off'REDACTED
  condition: REDACTED
  - condition: stateREDACTED
    entity_id: input_boolean.manual_lights_officeREDACTED
    state: "off"REDACTED
  action:REDACTED
  - service: light.turn_offREDACTED
    target:REDACTED
      entity_id: REDACTED
      - light.office_lightsREDACTED
  - service: switch.turn_offREDACTED
    target:REDACTED
      entity_id: REDACTED
      - switch.office_switchesREDACTED
REDACTED
- alias: Light Office on after MotionREDACTED
  trigger:REDACTED
    platform: stateREDACTED
    entity_id: binary_sensor.activity_in_officeREDACTED
    to: 'on'REDACTED
  condition: REDACTED
  - condition: stateREDACTED
    entity_id: input_boolean.manual_lights_officeREDACTED
    state: "off"REDACTED
  action:REDACTED
  - service: light.turn_onREDACTED
    target:REDACTED
      entity_id: REDACTED
      - light.office_lightsREDACTED
REDACTED
REDACTED
- alias: "Timerstop office lights manual"REDACTED
  id: "Timerstop office lights manual"REDACTED
  trigger:REDACTED
  - platform: eventREDACTED
    event_type: timer.finishedREDACTED
    event_data:REDACTED
      entity_id: timer.office_lights_manualREDACTED
  action:REDACTED
  - service: input_boolean.turn_offREDACTED
    target:REDACTED
      entity_id: REDACTED
      - input_boolean.manual_lights_officeREDACTED
    