######################################################################################################
# @Leroyby
# Original Repo : https://github.com/Leroyby/Homeassistant-Config
# Automations Office Lights
######################################################################################################

- alias: Light Office off after Motion
  trigger:
    platform: state
    entity_id: binary_sensor.activity_in_office
    to: 'off'
  condition: 
  - condition: state
    entity_id: binary_sensor.manual_lights_office
    state: "off"
  action:
  - service: light.turn_off
    target:
      entity_id: 
      - light.office_lights

- alias: Light Office on after Motion
  trigger:
    platform: state
    entity_id: binary_sensor.activity_in_office
    to: 'on'
  condition: 
  - condition: state
    entity_id: binary_sensor.manual_lights_office
    state: "off"
  - condition: state
    entity_id: sun.sun
    state: "below_horizon"
  action:
  - service: light.turn_on
    target:
      entity_id: 
      - light.office_lights


- alias: "Timerstop office lights manual"
  id: "Timerstop office lights manual"
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.office_lights_manual
  action:
  - service: input_boolean.turn_off
    target:
      entity_id: 
      - input_boolean.manual_lights_office
    