######################################################################################################
# @Leroyby
# Original Repo : https://github.com/Leroyby/Homeassistant-Config
# Automations System
######################################################################################################
- alias: System generate readme file
  trigger:
    - platform: time
      at: "23:15:00"
  condition:
  action:
  - service: readme.generate
