######################################################################################################REDACTED
# @LeroybyREDACTED
# Original Repo : https://github.com/Leroyby/Homeassistant-ConfigREDACTED
# Automations SystemREDACTED
######################################################################################################REDACTED
- alias: System generate readme fileREDACTED
  trigger:REDACTED
    - platform: timeREDACTED
      at: "23:15:00"REDACTED
  condition:REDACTED
  action:REDACTED
  - service: script.system_generate_readmeREDACTED
