######################################################################################################
# @Leroyby
# Original Repo : https://github.com/Leroyby/Homeassistant-Config
# binary sensors
######################################################################################################
- platform: template
  sensors:
    motion_detected:
      friendly_name: Any motion detected
      value_template: >
        {{ is_state("binary_sensor.activity_in_kitchen", "on")
            or is_state("binary_sensor.activity_in_livingroom", "on")
            or is_state("binary_sensor.activity_in_office", "on")
            or is_state("binary_sensor.activity_in_bedroom", "on") }}
            
    motion_detected_in_last_hour:
      friendly_name: Any motion detected in last hour
      value_template: >
        {{ is_state("binary_sensor.motion_detected", "on") }}
      delay_off: "01:00:00"

    someone_in_the_house_in_last_hour:
      friendly_name: Someone in the house in the last hour
      value_template: >
        {{ is_state("binary_sensor.motion_detected_in_last_hour", "on") }}

    activity_in_livingroom:
      friendly_name: Activity in the living room
      value_template: >
        {{ is_state("binary_sensor.motion_livingroom_occupancy", "on")
            or is_state("media_player.lg_webos_smart_tv", "on") }}
      delay_off: "00:01:00" 

    activity_in_kitchen:
      friendly_name: Activity in the kitchen
      value_template: >
        {{ is_state("binary_sensor.motion_livingroom_occupancy", "on") }}
      delay_off: "00:01:00"

    activity_in_office:
      friendly_name: Activity in the office
      value_template: >
        {{ is_state("media_player.lbxbox", "on")
            or is_state("switch.office_pc", "on")
            or is_state("binary_sensor.motion_office_occupancy", "on") }}
      delay_off: "00:01:00"

    activity_in_bedroom:
      friendly_name: Activity in the bedroom
      value_template: >
        {{ is_state("switch.bedroom_tv", "on")
           }}
      delay_off: "00:01:00"

    any_light_on:
      friendly_name: Any light is on
      value_template: >
        {% set office_lights_on = is_state("light.office_lights", "on") %}
        {% set bedroom_lights_on = is_state("light.bedroom_lights", "on") %}
        {% set living_roomlights_on = is_state("light.livingroom_lights", "on") %}
        {{ office_lights_on or bedroom_lights_on or living_room_lights_on }}

    anything_on:
      friendly_name: Anything is on
      value_template: >
        {% set light_on = is_state("binary_sensor.any_light_on", "on") %}
        {% set tv_on = is_state("media_player.lg_webos_smart_tv", "on") %}
        {{ light_on or tv_on }}
  
    no_one_home:
      friendly_name: No one is home
      value_template: >
        {{ not is_state("person.leroy", "home")
            and not is_state("person.USER2", "home") }}

- platform: workday
  country: CH
