######################################################################################################
# @Leroyby
# Original Repo : https://github.com/Leroyby/Homeassistant-Config
# Automations Livingroom Tuya Switch (4-Gang) (Entity: remote_livingroom_2)
######################################################################################################

- alias: livingroom button 1 light toggle
  trigger:
    platform: state
    entity_id: sensor.remote_livingroom_2_action
    to: '1_single' 
  condition: []
  action:
  - service: switch.toggle
    target:
      entity_id: switch.tv

- alias: livingroom button 1 lights cozy
  trigger:
    platform: state
    entity_id: sensor.remote_livingroom_2_action
    to: '1_double' 
  condition: []
  action:
  - service: script.turn_on
    target:
        entity_id: script.living_room_cozy_lights

- alias: livingroom button 1 light white
  trigger:
    platform: state
    entity_id: sensor.remote_livingroom_2_action
    to: '1_hold'
  condition: []
  action:
  - service: light.turn_on
    target:  
        entity_id: light.livingroom_sofa
    data:  
      brightness_pct: 100
      rgb_color: [255,255,255]  
      transition: 5   
###########################################
- alias: livingroom button 3 light sofa toggle
  trigger:
    platform: state
    entity_id: sensor.remote_livingroom_2_action
    to: '3_single' 
  condition: []
  action:
  - service: light.toggle
    target:
        entity_id: light.livingroom_sofa

- alias: livingroom button 3 light sofa brightness
  trigger:
    platform: state
    entity_id: sensor.remote_livingroom_2_action
    to: '3_double' 
  condition: []
  action:
  - service: light.turn_on
    target:
        entity_id: light.livingroom_sofa
    data:    
        brightness_step_pct: "{{ 20 if state_attr('light.livingroom_sofa', 'brightness')|int <= 250 else -80 }}"

- alias: livingroom button 3 light sofa white
  trigger:
    platform: state
    entity_id: sensor.remote_livingroom_2_action
    to: '3_hold'
  condition: []
  action:
  - service: light.turn_on
    target:  
        entity_id: light.livingroom_sofa
    data:  
      brightness_pct: 100
      rgb_color: [255,255,255]  
      transition: 5  
###########################################