######################################################################################################
# @Leroyby
# Original Repo : https://github.com/Leroyby/Homeassistant
# Automation livingroom IKEA 4-Button remote
######################################################################################################

- alias: change light with remote
  trigger:
    platform: state
    entity_id: sensor.remote_livingroom_action
    to: 'arrow_left_hold'
  condition:
  action:
  - service: input_text.set_value
    target:
      entity_id: 
      - input_text.remote_living_room_light_selection: Hi