######################################################################################################REDACTED
# @LeroybyREDACTED
# Original Repo : https://github.com/Leroyby/Homeassistant-ConfigREDACTED
# Automations Livingroom Ikea SwitchREDACTED
######################################################################################################REDACTED
- alias: Start TV Living RoomREDACTED
  trigger:REDACTED
    platform: stateREDACTED
    entity_id: sensor.tv_button_switch_livingroom_clickREDACTED
    to: 'on'REDACTED
  condition:REDACTED
  action:REDACTED
  - service: switch.turn_onREDACTED
    target:REDACTED
      entity_id: REDACTED
      - switch.tvREDACTED
REDACTED
- alias: Shutdown TV Living RoomREDACTED
  trigger:REDACTED
    platform: stateREDACTED
    entity_id: sensor.tv_button_switch_livingroom_clickREDACTED
    to: 'off'REDACTED
  condition:REDACTED
  action:REDACTED
  - service: switch.turn_offREDACTED
    target:REDACTED
      entity_id: REDACTED
      - switch.tv