######################################################################################################REDACTED
# @LeroybyREDACTED
# Original Repo : https://github.com/Leroyby/Homeassistant-ConfigREDACTED
# Automations Livingroom Tuya Switch (4-Gang) (Entity: remote_livingroom_2)REDACTED
######################################################################################################REDACTED
REDACTED
- alias: livingroom button 1 light toggleREDACTED
  trigger:REDACTED
    platform: stateREDACTED
    entity_id: sensor.remote_livingroom_2_actionREDACTED
    to: '1_single' REDACTED
  condition: []REDACTED
  action:REDACTED
  - service: switch.turn_offREDACTED
    target:REDACTED
      entity_id: switch.adaptive_lighting_livingroomREDACTED
  - service: light.toggleREDACTED
    target:REDACTED
        entity_id: light.living_room_lightsREDACTED
REDACTED
- alias: livingroom button 1 lights cozyREDACTED
  trigger:REDACTED
    platform: stateREDACTED
    entity_id: sensor.remote_livingroom_2_actionREDACTED
    to: '1_double' REDACTED
  condition: []REDACTED
  action:REDACTED
  - service: switch.turn_offREDACTED
    target:REDACTED
      entity_id: switch.adaptive_lighting_livingroomREDACTED
  - service: script.turn_onREDACTED
    target:REDACTED
        entity_id: script.living_room_cozy_lightsREDACTED
REDACTED
- alias: livingroom button 1 light whiteREDACTED
  trigger:REDACTED
    platform: stateREDACTED
    entity_id: sensor.remote_livingroom_2_actionREDACTED
    to: '1_hold'REDACTED
  condition: []REDACTED
  action:REDACTED
  - service: switch.turn_offREDACTED
    target:REDACTED
      entity_id: switch.adaptive_lighting_livingroomREDACTED
  - service: light.turn_onREDACTED
    target:  REDACTED
        entity_id: light.livingroom_tvREDACTED
    data:  REDACTED
      brightness: 255REDACTED
      kelvin: 5000 REDACTED
      transition: 5REDACTED
  - service: light.turn_onREDACTED
    target:  REDACTED
        entity_id: light.livingroom_sofaREDACTED
    data:  REDACTED
      brightness_pct: 100REDACTED
      rgb_color: [255,255,255]  REDACTED
      transition: 5   REDACTED
  - service: light.turn_onREDACTED
    target:  REDACTED
        entity_id: light.livingroom_tableREDACTED
    data:  REDACTED
      brightness_pct: 100REDACTED
      kelvin: 3300 REDACTED
      transition: 5REDACTED
###########################################REDACTED
REDACTED
- alias: livingroom button 2 light table toggleREDACTED
  trigger:REDACTED
    platform: stateREDACTED
    entity_id: sensor.remote_livingroom_2_actionREDACTED
    to: '2_single' REDACTED
  condition: []REDACTED
  action:REDACTED
  - service: switch.turn_offREDACTED
    target:REDACTED
      entity_id: switch.adaptive_lighting_livingroomREDACTED
  - service: light.toggleREDACTED
    target:REDACTED
        entity_id: light.livingroom_tableREDACTED
REDACTED
- alias: livingroom button 2 light table brightnessREDACTED
  trigger:REDACTED
    platform: stateREDACTED
    entity_id: sensor.remote_livingroom_2_actionREDACTED
    to: '2_double' REDACTED
  condition: []REDACTED
  action:REDACTED
  - service: switch.turn_offREDACTED
    target:REDACTED
      entity_id: switch.adaptive_lighting_livingroomREDACTED
  - service: light.turn_onREDACTED
    target:REDACTED
        entity_id: light.livingroom_tableREDACTED
    data:    REDACTED
        brightness_step_pct: "{{ 20 if state_attr('light.livingroom_table', 'brightness')|int <= 250 else -80 }}"REDACTED
REDACTED
- alias: livingroom button 2 light table whiteREDACTED
  trigger:REDACTED
    platform: stateREDACTED
    entity_id: sensor.remote_livingroom_2_actionREDACTED
    to: '2_hold'REDACTED
  condition: []REDACTED
  action:REDACTED
  - service: switch.turn_offREDACTED
    target:REDACTED
      entity_id: switch.adaptive_lighting_livingroomREDACTED
  - service: light.turn_onREDACTED
    target:  REDACTED
        entity_id: light.livingroom_tableREDACTED
    data:  REDACTED
      brightness_pct: 100REDACTED
      kelvin: 3300 REDACTED
      transition: 5      REDACTED
###########################################REDACTED
REDACTED
- alias: livingroom button 3 light sofa toggleREDACTED
  trigger:REDACTED
    platform: stateREDACTED
    entity_id: sensor.remote_livingroom_2_actionREDACTED
    to: '3_single' REDACTED
  condition: []REDACTED
  action:REDACTED
  - service: switch.turn_offREDACTED
    target:REDACTED
      entity_id: switch.adaptive_lighting_livingroomREDACTED
  - service: light.toggleREDACTED
    target:REDACTED
        entity_id: light.livingroom_sofaREDACTED
REDACTED
- alias: livingroom button 3 light sofa brightnessREDACTED
  trigger:REDACTED
    platform: stateREDACTED
    entity_id: sensor.remote_livingroom_2_actionREDACTED
    to: '3_double' REDACTED
  condition: []REDACTED
  action:REDACTED
  - service: switch.turn_offREDACTED
    target:REDACTED
      entity_id: switch.adaptive_lighting_livingroomREDACTED
  - service: light.turn_onREDACTED
    target:REDACTED
        entity_id: light.livingroom_sofaREDACTED
    data:    REDACTED
        brightness_step_pct: "{{ 20 if state_attr('light.livingroom_sofa', 'brightness')|int <= 250 else -80 }}"REDACTED
REDACTED
- alias: livingroom button 3 light sofa whiteREDACTED
  trigger:REDACTED
    platform: stateREDACTED
    entity_id: sensor.remote_livingroom_2_actionREDACTED
    to: '3_hold'REDACTED
  condition: []REDACTED
  action:REDACTED
  - service: switch.turn_offREDACTED
    target:REDACTED
      entity_id: switch.adaptive_lighting_livingroomREDACTED
  - service: light.turn_onREDACTED
    target:  REDACTED
        entity_id: light.livingroom_sofaREDACTED
    data:  REDACTED
      brightness_pct: 100REDACTED
      rgb_color: [255,255,255]  REDACTED
      transition: 5  REDACTED
###########################################REDACTED
REDACTED
- alias: livingroom button 4 light tv toggleREDACTED
  trigger:REDACTED
    platform: stateREDACTED
    entity_id: sensor.remote_livingroom_2_actionREDACTED
    to: '4_single' REDACTED
  condition: []REDACTED
  action:REDACTED
  - service: switch.turn_offREDACTED
    target:REDACTED
      entity_id: switch.adaptive_lighting_livingroomREDACTED
  - service: light.toggleREDACTED
    target:REDACTED
        entity_id: light.livingroom_tvREDACTED
REDACTED
- alias: livingroom button 4 light tv brightnessREDACTED
  trigger:REDACTED
    platform: stateREDACTED
    entity_id: sensor.remote_livingroom_2_actionREDACTED
    to: '4_double' REDACTED
  condition: []REDACTED
  action:REDACTED
  - service: switch.turn_offREDACTED
    target:REDACTED
      entity_id: switch.adaptive_lighting_livingroomREDACTED
  - service: light.turn_onREDACTED
    target:REDACTED
        entity_id: light.livingroom_tvREDACTED
    data:    REDACTED
        brightness_step_pct: "{{ 20 if state_attr('light.livingroom_tv', 'brightness')|int <= 250 else -80 }}"REDACTED
- alias: livingroom button 4 light tv whiteREDACTED
  trigger:REDACTED
    platform: stateREDACTED
    entity_id: sensor.remote_livingroom_2_actionREDACTED
    to: '4_hold'REDACTED
  condition: []REDACTED
  action:REDACTED
  - service: switch.turn_offREDACTED
    target:REDACTED
      entity_id: switch.adaptive_lighting_livingroomREDACTED
  - service: light.turn_onREDACTED
    target:  REDACTED
        entity_id: light.livingroom_tvREDACTED
    data:  REDACTED
      brightness: 255REDACTED
      kelvin: 5000 REDACTED
      transition: 5REDACTED
REDACTED
 ###########################################REDACTED
REDACTED
- alias: livingroom turn adaptive light onREDACTED
  trigger:REDACTED
    platform: stateREDACTED
    entity_id: light.living_room_lightsREDACTED
    to: 'off' REDACTED
  condition: []REDACTED
  action:REDACTED
  - service: switch.turn_onREDACTED
    target:REDACTED
      entity_id: switch.adaptive_lighting_livingroom