######################################################################################################
# @Leroyby
# Original Repo : https://github.com/Leroyby/Homeassistant-Config
# Automations Livingroom Tuya Switch (4-Gang) (Entity: remote_livingroom_2)
######################################################################################################

- alias: livingroom button 1 light toggle
  trigger:
    platform: state
    entity_id: sensor.remote_livingroom_2_action
    to: '1_single' 
  condition: []
  action:
  - service: switch.turn_off
    target:
      entity_id: switch.adaptive_lighting_livingroom
  - service: light.toggle
    target:
        entity_id: light.living_room_lights

- alias: livingroom button 1 lights cozy
  trigger:
    platform: state
    entity_id: sensor.remote_livingroom_2_action
    to: '1_double' 
  condition: []
  action:
  - service: switch.turn_off
    target:
      entity_id: switch.adaptive_lighting_livingroom
  - service: script.turn_on
    target:
        entity_id: script.living_room_cozy_lights

- alias: livingroom button 1 light white
  trigger:
    platform: state
    entity_id: sensor.remote_livingroom_2_action
    to: '1_hold'
  condition: []
  action:
  - service: switch.turn_off
    target:
      entity_id: switch.adaptive_lighting_livingroom
  - service: light.turn_on
    target:  
        entity_id: light.livingroom_tv
    data:  
      brightness: 255
      kelvin: 5000 
      transition: 5
  - service: light.turn_on
    target:  
        entity_id: light.livingroom_sofa
    data:  
      brightness_pct: 100
      rgb_color: [255,255,255]  
      transition: 5   
  - service: light.turn_on
    target:  
        entity_id: light.livingroom_table
    data:  
      brightness_pct: 100
      kelvin: 3300 
      transition: 5
###########################################

- alias: livingroom button 2 light table toggle
  trigger:
    platform: state
    entity_id: sensor.remote_livingroom_2_action
    to: '2_single' 
  condition: []
  action:
  - service: switch.turn_off
    target:
      entity_id: switch.adaptive_lighting_livingroom
  - service: light.toggle
    target:
        entity_id: light.livingroom_table

- alias: livingroom button 2 light table brightness
  trigger:
    platform: state
    entity_id: sensor.remote_livingroom_2_action
    to: '2_double' 
  condition: []
  action:
  - service: switch.turn_off
    target:
      entity_id: switch.adaptive_lighting_livingroom
  - service: light.turn_on
    target:
        entity_id: light.livingroom_table
    data:    
        brightness_step_pct: "{{ 20 if state_attr('light.livingroom_tv', 'brightness')|int <= 250 else -80 }}"

- alias: livingroom button 2 light table white
  trigger:
    platform: state
    entity_id: sensor.remote_livingroom_2_action
    to: '2_hold'
  condition: []
  action:
  - service: switch.turn_off
    target:
      entity_id: switch.adaptive_lighting_livingroom
  - service: light.turn_on
    target:  
        entity_id: light.livingroom_table
    data:  
      brightness_pct: 100
      kelvin: 3300 
      transition: 5      
###########################################

- alias: livingroom button 3 light sofa toggle
  trigger:
    platform: state
    entity_id: sensor.remote_livingroom_2_action
    to: '3_single' 
  condition: []
  action:
  - service: switch.turn_off
    target:
      entity_id: switch.adaptive_lighting_livingroom
  - service: light.toggle
    target:
        entity_id: light.livingroom_sofa

- alias: livingroom button 3 light sofa brightness
  trigger:
    platform: state
    entity_id: sensor.remote_livingroom_2_action
    to: '3_double' 
  condition: []
  action:
  - service: switch.turn_off
    target:
      entity_id: switch.adaptive_lighting_livingroom
  - service: light.turn_on
    target:
        entity_id: light.livingroom_sofa
    data:    
        brightness_step_pct: "{{ 20 if state_attr('light.livingroom_tv', 'brightness')|int <= 250 else -80 }}"

- alias: livingroom button 3 light sofa white
  trigger:
    platform: state
    entity_id: sensor.remote_livingroom_2_action
    to: '3_hold'
  condition: []
  action:
  - service: switch.turn_off
    target:
      entity_id: switch.adaptive_lighting_livingroom
  - service: light.turn_on
    target:  
        entity_id: light.livingroom_sofa
    data:  
      brightness_pct: 100
      rgb_color: [255,255,255]  
      transition: 5  
###########################################

- alias: livingroom button 4 light tv toggle
  trigger:
    platform: state
    entity_id: sensor.remote_livingroom_2_action
    to: '4_single' 
  condition: []
  action:
  - service: switch.turn_off
    target:
      entity_id: switch.adaptive_lighting_livingroom
  - service: light.toggle
    target:
        entity_id: light.livingroom_tv

- alias: livingroom button 4 light tv brightness
  trigger:
    platform: state
    entity_id: sensor.remote_livingroom_2_action
    to: '4_double' 
  condition: []
  action:
  - service: switch.turn_off
    target:
      entity_id: switch.adaptive_lighting_livingroom
  - service: light.turn_on
    target:
        entity_id: light.livingroom_tv
    data:    
        brightness_step_pct: "{{ 20 if state_attr('light.livingroom_tv', 'brightness')|int <= 250 else -80 }}"
- alias: livingroom button 4 light tv white
  trigger:
    platform: state
    entity_id: sensor.remote_livingroom_2_action
    to: '4_hold'
  condition: []
  action:
  - service: switch.turn_off
    target:
      entity_id: switch.adaptive_lighting_livingroom
  - service: light.turn_on
    target:  
        entity_id: light.livingroom_tv
    data:  
      brightness: 255
      kelvin: 5000 
      transition: 5

 ###########################################

- alias: livingroom turn adaptive light on
  trigger:
    platform: state
    entity_id: light.living_room_lights
    to: 'off' 
  condition: []
  action:
  - service: switch.turn_on
    target:
      entity_id: switch.adaptive_lighting_livingroom