######################################################################################################
# @Leroyby
# Original Repo : https://github.com/Leroyby/Homeassistant
# Automation Office Aqara Button 4-Button switch
######################################################################################################

- alias: Tuya 1 single
  trigger:
    platform: state
    entity_id: sensor.
    to: 'single' 
  condition: []
  action:
  - service: script.office_light
  - service: input_boolean.turn_on
    target:
      entity_id: 
      - input_boolean.manual_lights_office
  - service: timer.start
    target:
      entity_id: timer.office_lights_manual  



