######################################################################################################REDACTED
# @LeroybyREDACTED
# Original Repo : https://github.com/Leroyby/Homeassistant-ConfigREDACTED
# Automation Office Aqara Button REDACTED
######################################################################################################REDACTED
REDACTED
- alias: Office Button Lights REDACTED
  trigger:REDACTED
    platform: stateREDACTED
    entity_id: sensor.aqara_button_office_actionREDACTED
    to: 'single' REDACTED
  condition: []REDACTED
  action:REDACTED
  - service: light.toggleREDACTED
    target:REDACTED
        entity_id: light.office_lightsREDACTED
  - service: timer.startREDACTED
    target:REDACTED
        entity_id: timer.office_lights_manual  REDACTED
REDACTED
- alias: Office Button Switch PC REDACTED
  trigger:REDACTED
    platform: stateREDACTED
    entity_id: sensor.aqara_button_office_actionREDACTED
    to: 'double' REDACTED
  condition: []REDACTED
  action:REDACTED
    service: switch.toggleREDACTED
    target:REDACTED
      entity_id: switch.office_pcREDACTED
REDACTED
# not working as intendetREDACTED
# Zigbee2MQTT doenst get tripple click on buttonREDACTED
- alias: Office Button Switch Xbox REDACTED
  trigger:REDACTED
    platform: stateREDACTED
    entity_id: sensor.aqara_button_office_actionREDACTED
    to: 'triple' REDACTED
  condition: []REDACTED
  action:REDACTED
    service: switch.toggleREDACTED
    target:REDACTED
      entity_id: switch.office_xboxREDACTED
REDACTED
REDACTED
- alias: office total off remoteREDACTED
  trigger:REDACTED
    platform: stateREDACTED
    entity_id: sensor.aqara_button_office_actionREDACTED
    to: 'hold' REDACTED
  condition: []REDACTED
  action:REDACTED
    service: script.office_offREDACTED
REDACTED
REDACTED
