homeassistant: true
mqtt:
  server: mqtt://core-mosquitto:1883
  user: addons
  password: Uoloo5ud9oot8Gee6iulei4eec9gie3auhoongoph3eshuew8aewohche1Iphaih
serial:
  port: /dev/ttyACM0
  adapter: deconz
frontend:
  port: 8099
devices:
  '0x00158d0008048909':
    friendly_name: Aqara Button Office
    legacy: false
  '0x003c84fffe282720':
    friendly_name: button_bedroom
  '0x00158d0007e2122f':
    friendly_name: motion_livingroom
  '0x94deb8fffe60c570':
    friendly_name: Livingroom_Deckenfluter_TV
  '0x9035eafffe2b5f86':
    friendly_name: '0x9035eafffe2b5f86'
  '0x086bd7fffe3c5fde':
    friendly_name: tv_button_switch_livingroom
  '0x086bd7fffe51879e':
    friendly_name: TV
  '0x00158d00086521c7':
    friendly_name: temperature_livingroom_tv
  '0x000b57fffe3126b6':
    friendly_name: remote_bedroom
advanced:
  log_level: info
shell_command:
  pushupdates_github: /bin/bash /root/addons/Tools/pushupdates.sh
