homeassistant: true
mqtt:
  server: mqtt://core-mosquitto:1883
  user: addons
  password: Uoloo5ud9oot8Gee6iulei4eec9gie3auhoongoph3eshuew8aewohche1Iphaih
serial:
  port: /dev/ttyACM0
  adapter: deconz
frontend:
  port: 8099
devices:
  '0x00158d0008048909':
    friendly_name: Aqara Button Office
    legacy: false
  '0x003c84fffe282720':
    friendly_name: button_bedroom
  '0x00158d0007e2122f':
    friendly_name: motion_livingroom
  '0x94deb8fffe60c570':
    friendly_name: Livingroom_Deckenfluter_TV
  '0x9035eafffe2b5f86':
    friendly_name: remote_livingroom
  '0x086bd7fffe3c5fde':
    friendly_name: tv_button_switch_livingroom
  '0x086bd7fffe51879e':
    friendly_name: TV
  '0x00158d00086521c7':
    friendly_name: temperature_livingroom_tv
  '0x000b57fffe3126b6':
    friendly_name: remote_bedroom
  '0x00158d0007ec9426':
    friendly_name: Vibration_office_1
  '0xb4e3f9fffe14e4a3':
    friendly_name: remote_livingroom_2
  '0x8cf681fffea9c5d2':
    friendly_name: Bedroom_thermostat
  '0x00158d0008cf22d0':
    friendly_name: motion_office
  '0x00158d0008cf2323':
    friendly_name: motion_livingroom_cabinet
  '0x00158d0008e1c947':
    friendly_name: contact_livingroom_cabinet
  '0x00158d0008cec364':
    friendly_name: temperature_bedroom_2
  '0x00158d0008cec36e':
    friendly_name: temperature_office
  '0x00158d0008c99136':
    friendly_name: temperature_outdoor
advanced:
  log_level: info
shell_command:
  pushupdates_github: /bin/bash /root/addons/Tools/pushupdates.sh
permit_join: false
