title: HQ-BY-REDACTED
views:
  - theme: Backend-selected
    title: Start
    path: v
    badges: []
    cards: []
  - theme: Backend-selected
    title: Floor
    path: floor
    type: panel
    badges: []
    cards:
      - type: picture-elements
        image: local/images/lights_off.png
        elements:
          - type: image
            entity: light.livingroom_sofa
            style:
              left: 50%
              top: 50%
              width: 100%
            state_image:
              'on': /local/images/light_sofa_on.png
              'off': /local/images/home_transparent.png
          - type: image
            entity: light.livingroom_table
            style:
              left: 50%
              top: 50%
              width: 100%
            state_image:
              'on': /local/images/light_table_on.png
              'off': /local/images/home_transparent.png
          - type: image
            entity: light.livingroom_tv
            style:
              left: 50%
              top: 50%
              width: 100%
            state_image:
              'on': /local/images/light_tv_on.png
              'off': /local/images/home_transparent.png
          - type: image
            entity: light.office_lights
            style:
              left: 50%
              top: 50%
              width: 100%
            state_image:
              'on': /local/images/light_office_on.png
              'off': /local/images/home_transparent.png
          - type: image
            entity: light.bedroom_lights
            style:
              left: 50%
              top: 50%
              width: 100%
            state_image:
              'on': /local/images/light_bedroom_on.png
              'off': /local/images/home_transparent.png
          - type: state-icon
            entity: light.livingroom_tv
            tap_action:
              action: toggle
            style:
              left: 59%
              top: 58%
              '--mdc-icon-size': 25px
            state_image:
              'on': /local/images/light_tv_on.png
              'off': /local/images/home_transparent.png
          - type: state-icon
            entity: light.office_lights
            tap_action:
              action: toggle
            style:
              left: 49%
              top: 69%
              '--mdc-icon-size': 25px
            state_image:
              'on': /local/images/light_office_on.png
              'off': /local/images/home_transparent.png
          - type: state-icon
            entity: light.bedroom_lights
            tap_action:
              action: toggle
            style:
              left: 45%
              top: 83%
              '--mdc-icon-size': 25px
            state_image:
              'on': /local/images/light_bedroom_on.png
              'off': /local/images/home_transparent.png
          - type: state-icon
            entity: light.livingroom_table
            tap_action:
              action: toggle
            style:
              left: 46%
              top: 30%
              '--mdc-icon-size': 25px
            state_image:
              'on': /local/images/light_table_on.png
              'off': /local/images/home_transparent.png
          - type: state-icon
            entity: light.livingroom_sofa
            tap_action:
              action: toggle
            style:
              left: 62%
              top: 44.5%
              '--mdc-icon-size': 25px
            state_image:
              'on': /local/images/light_sofa_on.png
              'off': /local/images/home_transparent.png
          - type: state-badge
            entity: sensor.temperature_livingroom_average
            style:
              left: 49%
              top: 15%
              color: transparent
              opacity: 0.6
              transform: scale(0.6,0.6)
          - type: state-badge
            entity: sensor.temperature_office_average
            style:
              left: 50%
              top: 55%
              color: transparent
              opacity: 0.6
              transform: scale(0.6,0.6)
          - type: state-badge
            entity: sensor.temperature_bedroom
            style:
              left: 48%
              top: 75%
              color: transparent
              opacity: 0.6
              transform: scale(0.6,0.6)